In [1]:
from datasets import load_from_disk
from openai import AzureOpenAI

/media/research/yrl_aida_users/poddubny/poddubnyy/postgraduate/semtab_serializer/.myenv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [8]:
import sys
import os

# Добавляем корневую директорию проекта в sys.path
sys.path.append(os.path.dirname(os.path.abspath('/media/research/yrl_aida_users/poddubny/poddubnyy/postgraduate/semtab_serializer/tests')))

In [4]:
dataset = load_from_disk('none_filtered_new_dataset/')
dataset

Dataset({
    features: ['id', 'statement', 'label', 'table_caption', 'table_text', 'pandas_code', 'pandas_eval', 'nlsep_query', 'semtab_query'],
    num_rows: 88116
})

In [42]:
dataset[0]

NameError: name 'dataset' is not defined

In [5]:

system_prompt = '''You are a Python expert specializing in pandas. Your task is to translate the
given natural language statement into a single-line pandas expression. This
expression must be valid and executable to verify the truth of the statement
using the provided table. Consider the following:
1. The table is represented as a pandas DataFrame named df.
2. Do not include explanations, comments, or multiline outputs.
3. Ensure the output is concise, correct, and when run outputs either True or
False, and strictly in the following Json Format with a single key "PANDA":
"PANDA": "<your Pandas code>"
'''

In [6]:
print(system_prompt)

You are a Python expert specializing in pandas. Your task is to translate the
given natural language statement into a single-line pandas expression. This
expression must be valid and executable to verify the truth of the statement
using the provided table. Consider the following:
1. The table is represented as a pandas DataFrame named df.
2. Do not include explanations, comments, or multiline outputs.
3. Ensure the output is concise, correct, and when run outputs either True or
False, and strictly in the following Json Format with a single key "PANDA":
"PANDA": "<your Pandas code>"

In [7]:
from openai import OpenAI
def send_message(message,max_tokens=2000,top_p=0.9,temperature=0.5,server_url="http://127.0.0.1:8800/v1",api_key="dummy",
                 model_name='deepseek-ai/deepseek-coder-7b-instruct-v1.5',system_prompt='', stop = ["Observation:","\n\n\n\n","\n \n \n"]):
    client = OpenAI(base_url=server_url, api_key=api_key)
    model_input = [
        { 'role': 'system', 'content': system_prompt},
        { 'role': 'user', 'content': message}
    ]
    try:
        print(f"Generating content with model: {model_name}",)
        
        response = client.chat.completions.create(
            model=model_name,
            messages=model_input,
            temperature=temperature,
            max_tokens=max_tokens,
            top_p=top_p,
            stop = stop
        )
        
        return True, response.choices[0].message.content

    except Exception as e:
        print("Failed to call LLM: " + str(e))
        time.sleep(6)
        if hasattr(e, 'response'):
            error_info = e.response.json()  
            code_value = error_info['error']['code']
        else:
            code_value = "context_length_exceeded"
        print("Retrying ...")
        return False, None

In [8]:
import json
import pandas as pd
from io import StringIO
from tqdm import tqdm

In [ ]:

count = 0
corrects_sep = 0
corrects_sem = 0
for entry in tqdm(dataset):
    total += 1
    df = pd.read_csv(StringIO(entry['table_text']), delimiter='#')
    success,response_sep = send_message(f'{entry["statement"]} {entry["nlsep_query"]}',
                                       system_prompt=system_prompt)
    if success:
        pandas_eval = str(bool(eval(response_sep)))
        if str(bool(entry['label'])) == str(pandas_eval):
            corrects_sep += 1
        else:
            print(response_sep)

    success,response_sem = send_message(f'{entry["statement"]} {entry["semtab_query"]}',
                                       system_prompt=system_prompt)
    if success:
        pandas_eval = str(bool(eval(response_sem)))
        if str(bool(entry['label'])) == str(pandas_eval):
            response_sem += 1
        else:
            print(corrects_sem)

print(corrects, total, corrects / total)

In [76]:
import re

def parse_panda_code(input_string):
    """
    Парсит строку и извлекает код, который находится внутри конструкции "PANDA": <код>
    Поддерживает различные форматы: JSON, простой текст, Markdown
    
    Args:
        input_string (str): Входная строка для парсинга
        
    Returns:
        str: Извлеченный код или пустая строка, если код не найден
    """
    # Сначала попробуем найти JSON объект с PANDA
    json_pattern = r'\{[^{}]*PANDA":\s*(.+?)(?:\n|$)?\}'
    json_match = re.search(json_pattern, input_string, re.DOTALL)
    code = None
    pattern = r'"PANDA":\s*(.+?)(?:\n|$)'
    if json_match:
        code = json_match.group(1).strip()
    else:
        match = re.search(pattern, input_string, re.DOTALL)
        if match:
        # Извлекаем код и убираем лишние пробелы по краям
            code = match.group(1).strip()
        # Заменяем одинарные кавычки внутри строки для корректного парсинга JSON

    # Если JSON не найден или не распарсился, используем старый метод
    # Паттерн для поиска кода после "PANDA": 
    # Ищет "PANDA": за которым следует пробел, затем код до конца строки или до следующего символа
    if code != None:
    # Убираем возможные кавычки вокруг кода
        if code.startswith('"') and code.endswith('"'):
            code = code[1:-1]
        elif code.startswith("'") and code.endswith("'"):
            code = code[1:-1]
            
        return code
    
    return ""

In [81]:
corrects_sep = 0

df = pd.read_csv(StringIO(dataset[0]['table_text']), delimiter='#')
success,response_sep = send_message(f'{dataset[0]["statement"]} {dataset[0]["nlsep_query"]}',
                                   system_prompt=system_prompt)
if success:
    pandas_eval = str(bool(eval(parse_panda_code(response_sep))))
    if str(bool(dataset[0]['label'])) == str(pandas_eval):
        corrects_sep += 1
    else:
        print(response_sep)

success,response_sem = send_message(f'{dataset[0]["statement"]} {dataset[0]["semtab_query"]}',
                                   system_prompt=system_prompt)

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Here is a single-line pandas expression that checks if Haroldo is mentioned as a Brazil scorer for two different games:

```json
"PANDA": "df['brazil scorers'].apply(lambda x: 'haroldo' in x.split(', ')).sum() >= 2"
```

This expression splits the 'brazil scorers' column into a list of scorers for each game, checks if 'haroldo' is in the list, and then sums up the True values to see if he is mentioned as a scorer for at least two games.

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

In [42]:
print(response_sep)

```json
"PANDA": "df['brazil scorers'].str.contains('haroldo', na=False).sum() > 1"
```
This code checks if 'haroldo' is mentioned as a Brazil scorer for more than 1 game. It uses the str.contains method to check if 'haroldo' is present in the 'brazil scorers' column and then sums up the number of True values, indicating how many games 'haroldo' scored for Brazil.

In [43]:
dataset[0]['label']

1

In [44]:
str(bool(eval(parse_panda_code(response_sep))))

'True'

In [45]:
parse_panda_code(response_sep)

"df['brazil scorers'].str.contains('haroldo', na=False).sum() > 1"

In [90]:
df['brazil scorers'].apply(lambda x: 'haroldo' in x.split(', ')).sum() >= 2

np.False_

In [82]:
print(response_sem)

```json
"PANDA": "df['brazil scorers'].apply(lambda x: 'haroldo' in x.split(',')).sum() > 1"
```
This code checks if 'haroldo' is mentioned as a scorer for more than one game in the 'brazil scorers' column of the DataFrame.

In [83]:
corrects_sem = 0
if success:
    pandas_eval = str(bool(eval(parse_panda_code(response_sem))))
    if str(bool(dataset[0]['label'])) == str(parse_panda_code(pandas_eval)):
        corrects_sem += 1
    else:
        print(corrects_sem)

0

In [77]:
parse_panda_code(response_sem)

"df['brazil scorers'].str.contains('haroldo', na=False).sum() > 1"

In [65]:
response_sem

'Here is the single-line pandas expression based on the given statement:\n\n```json\n{"PANDA": "df[\'brazil scorers\'].str.contains(\'haroldo\', na=False).sum() > 1"}\n```\n\nThis expression checks if \'haroldo\' is mentioned as a Brazil scorer for more than 1 game in the \'brazil scorers\' column of the DataFrame df.\n'

In [66]:
pattern = r'"PANDA":\s*(.+?)(?:\n|$)'
    
    # Используем поиск с флагом re.DOTALL для работы с многострочным кодом
match = re.search(pattern, '''Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Here is a Python pandas code snippet that checks if Haroldo is mentioned as a Brazil scorer for more than one game:
```json
"PANDA": "df['brazil scorers'].str.contains('Haroldo', na=False).sum() > 1"
```
This code uses the pandas `str.contains` method to check if 'Haroldo' is in the 'brazil scorers' column. The `na=False` parameter ensures that NaN values are not considered as matches. The `sum()` method is then used to count the number of True values returned by the `contains` method, which corresponds to the number of times 'Haroldo' is mentioned as a Brazil scorer. The result is checked if it's greater than 1.''',
                  re.DOTALL)

In [67]:
code = match.group(1).strip()

In [68]:
code

'"df[\'brazil scorers\'].str.contains(\'Haroldo\', na=False).sum() > 1"'

In [73]:
match.group()

'"PANDA": "df[\'brazil scorers\'].str.contains(\'Haroldo\', na=False).sum() > 1"\n'

In [85]:
bool(eval(parse_panda_code(response_sem)))

False

In [86]:
bool(dataset[0]['label'])

True

In [167]:
from datasets import load_from_disk
from openai import OpenAI
import sys
import os
import json
import pandas as pd
from io import StringIO
from tqdm import tqdm
import re
# Добавляем корневую директорию проекта в sys.path
sys.path.append(os.path.dirname(os.path.abspath('/media/research/yrl_aida_users/poddubny/poddubnyy/postgraduate/semtab_serializer/tests')))

system_prompt = '''You are a Python expert specializing in pandas. Your task is to translate the
given natural language statement into a single-line pandas expression. This
expression must be valid and executable to verify the truth of the statement
using the provided table. Consider the following:
1. The table is represented as a pandas DataFrame named df.
2. Do not include explanations, comments, or multiline outputs.
3. Ensure the output is concise, correct, and when run outputs either True or
False, and strictly in the following Json Format with a single key "PANDA":
"PANDA": "<your Pandas code>"
'''
system_correcting_prompt = '''
You are a Python expert specializing in pandas. Your task is to correct a pandas code that translates 
a given natural language statement into a pandas
expression. The input data, code, along with the specific error it contains, is provided.
Your corrected pandas_code must be valid and executable by running the code
snippet str(bool(eval(pandas_code))) ensuring it accurately evaluates the truth
of the statement using the provided table with no errors.
Make sure the pandas_code is of type boolean. Consider the following:
1. The table is represented as a pandas DataFrame named df.
2. Do not include explanations, comments, or multiline outputs.
3. Ensure the output is concise, correct, and when run outputs either True or
False, and strictly in the following Json Format with a single key "CORRECT PANDA": 
"CORRECT PANDA": "<your Pandas code>"
'''


def send_message(message,max_tokens=500,top_p=0.9,temperature=0.5,server_url="http://127.0.0.1:8800/v1",api_key="dummy",
                 model_name='deepseek-ai/deepseek-coder-7b-instruct-v1.5',system_prompt='', stop = ["Observation:","\n\n\n\n","\n \n \n"]):
    client = OpenAI(base_url=server_url, api_key=api_key)
    model_input = [
        { 'role': 'system', 'content': system_prompt},
        { 'role': 'user', 'content': message}
    ]
    try:
        print(f"Generating content with model: {model_name}",)
        
        response = client.chat.completions.create(
            model=model_name,
            messages=model_input,
            temperature=temperature,
            max_tokens=max_tokens,
            top_p=top_p,
            stop = stop
        )
        
        return True, response.choices[0].message.content

    except Exception as e:
        print("Failed to call LLM: " + str(e))
        time.sleep(6)
        if hasattr(e, 'response'):
            error_info = e.response.json()  
            code_value = error_info['error']['code']
        else:
            code_value = "context_length_exceeded"
        print("Retrying ...")
        return False, None

def parse_panda_code(input_string):
    """
    Парсит строку и извлекает код, который находится внутри конструкции "PANDA": <код>
    Поддерживает различные форматы: JSON, простой текст, Markdown
    
    Args:
        input_string (str): Входная строка для парсинга
        
    Returns:
        str: Извлеченный код или пустая строка, если код не найден
    """
    # Сначала попробуем найти JSON объект с PANDA
    json_pattern = r'\{[^{}]*PANDA":\s*(.+?)(?:\n|$)?\}'
    json_match = re.search(json_pattern, input_string, re.DOTALL)
    code = None
    pattern = r'"PANDA":\s*(.+?)(?:\n|$)'
    if json_match:
        code = json_match.group(1).strip()
    else:
        match = re.search(pattern, input_string, re.DOTALL)
        if match:
        # Извлекаем код и убираем лишние пробелы по краям
            code = match.group(1).strip()
        # Заменяем одинарные кавычки внутри строки для корректного парсинга JSON

    # Если JSON не найден или не распарсился, используем старый метод
    # Паттерн для поиска кода после "PANDA": 
    # Ищет "PANDA": за которым следует пробел, затем код до конца строки или до следующего символа
    if code != None:
    # Убираем возможные кавычки вокруг кода
        if code.startswith('"') and code.endswith('"'):
            code = code[1:-1]
        elif code.startswith("'") and code.endswith("'"):
            code = code[1:-1]
            
        return code
    
    return ""

def correct_code(df,input_data,code_str,error_str,iter_id=0,system_correcting_prompt='',stop= ["Observation:","\n\n\n\n","\n \n \n"],
                max_tokens=500,top_p=0.9,temperature=0.5,server_url="http://127.0.0.1:8800/v1",api_key="dummy",
                model_name='deepseek-ai/deepseek-coder-7b-instruct-v1.5',max_iter=3):
    if iter_id<max_iter:
        success,response = send_message(f'INPUT DATA: {input_data}\n CODE: {code_str}\n ERROR: {error_str}',stop= stop,
                    max_tokens=max_tokens,top_p=top_p,temperature=temperature,server_url=server_url,api_key=api_key,
                    model_name=model_name, system_prompt=system_correcting_prompt)
        if success:
            correct_code = parse_panda_code(response_sep)
            try:
                pandas_eval = str(bool(eval(correct_code)))
                return True,correct_code, response
            except Exception as e:
                print(e)
                return correct_code(df,correct_code,str(e),iter_id=iter_id+1,max_tokens=max_tokens,top_p=top_p,
                             temperature=temperature, server_url=server_url,api_key=api_key,model_name=model_name, 
                             system_correcting_prompt=system_correcting_prompt,max_iter=max_iter)
                
        else:
            print('success correcting error')
            return correct_code(df,correct_code,str(e),iter_id=iter_id+1,max_tokens=max_tokens,top_p=top_p,
                             temperature=temperature, server_url=server_url,api_key=api_key,model_name=model_name, 
                             system_correcting_prompt=system_correcting_prompt,max_iter=max_iter)
    else:
        print(f'end of iter {iter_id}, max iter is {max_iter}')
        return False, code_str, None

system_correcting_prompt
def dataset_processing(entry,query_field=None,system_correcting_prompt='',system_prompt=''):
    df = pd.read_csv(StringIO(entry['table_text']), delimiter='#')
    success,response_sep = send_message(entry[f"{query_field}_query"],
                                       system_prompt=system_prompt)

    entry[f'{query_field}_answ'] = 'None'
    entry[f'{query_field}_label'] = 'None'
    entry[f'{query_field}_answ_correct'] = 'None'

    
    if success:
        entry[f'{query_field}_answ'] = response_sep
        try:
            code = parse_panda_code(response_sep)
            try:
            
                pandas_eval = str(bool(eval(code)))
                entry[f'{query_field}_label'] = str(pandas_eval)
            except Exception as e:
                print('EEEERRRRRRR', entry['id'])
                print(e)
                success_correcting, new_code, correcting_response = correct_code(df,entry[f"{query_field}_query"],
                                             correct_code,str(e),
                                             system_correcting_prompt=system_correcting_prompt)
                if success_correcting:
                    pandas_eval = str(bool(eval(new_code)))
                    entry[f'{query_field}_label'] = str(pandas_eval)
                    entry[f'{query_field}_answ_correct'] = correcting_response
        except Exception as e:
            print (e)
        
    return entry

#def dataset_processing(entry):
#    df = pd.read_csv(StringIO(entry['table_text']), delimiter='#')
#    success,response_sep = send_message(f'{entry["statement"]} {entry["nlsep_query"]}',
#                                       system_prompt=system_prompt)
#    if success:
#        entry['sep_answ'] = response_sep
#        pandas_eval = str(bool(eval(parse_panda_code(response_sep))))
#        entry['sep_label'] = str(pandas_eval)
#    else:
#        entry['sep_answ'] = 'None'
#        entry['sep_label'] = 'None'
#        
#    success,response_sem = send_message(f'{entry["statement"]} {entry["semtab_query"]}',
#                                       system_prompt=system_prompt)
#   if success:
#       entry['sem_answ'] = response_sem
#        pandas_eval = str(bool(eval(parse_panda_code(response_sem))))
#        entry['sem_label'] = str(pandas_eval)
#    else:
#        entry['sem_answ'] = 'None'
#        entry['sem_label'] = 'None'
#dataset = load_from_disk('none_filtered_new_dataset/')
#dataset2 = dataset.map(dataset_processing)

In [97]:
type(success)

bool

In [124]:
process_data = load_from_disk('answer_gen_semtab_none_filtered_new_dataset')
process_data

Dataset({
    features: ['id', 'statement', 'label', 'table_caption', 'table_text', 'pandas_code', 'pandas_eval', 'nlsep_query', 'semtab_query', 'semtab_answ', 'semtab_label'],
    num_rows: 88116
})

In [127]:
dd = process_data.filter(lambda x: True if x['semtab_answ']!='None' else False,num_proc=17)
dd

Dataset({
    features: ['id', 'statement', 'label', 'table_caption', 'table_text', 'pandas_code', 'pandas_eval', 'nlsep_query', 'semtab_query', 'semtab_answ', 'semtab_label'],
    num_rows: 88116
})

In [128]:
dd = process_data.filter(lambda x: True if x['semtab_label']!='None' else False,num_proc=17)
dd

Filter (num_proc=17): 100%|██████████| 88116/88116 [00:00<00:00, 151805.97 examples/s]

Dataset({
    features: ['id', 'statement', 'label', 'table_caption', 'table_text', 'pandas_code', 'pandas_eval', 'nlsep_query', 'semtab_query', 'semtab_answ', 'semtab_label'],
    num_rows: 62012
})

In [129]:
dd.shape[0]/process_data.shape[0]*100

70.37541422670117

In [130]:
true = dd.filter(lambda x : True if x['semtab_label']==str(bool(x['label'])) else False,num_proc=17)

Filter (num_proc=17): 100%|██████████| 62012/62012 [00:00<00:00, 98299.48 examples/s]

In [132]:
true.shape[0]/process_data.shape[0]*100

40.90176585410141

In [131]:
true.shape[0]/dd.shape[0]*100

58.11939624588789

In [134]:
process_data = load_from_disk('answer_gen_nlsep_none_filtered_new_dataset/')
process_data

Dataset({
    features: ['id', 'statement', 'label', 'table_caption', 'table_text', 'pandas_code', 'pandas_eval', 'nlsep_query', 'semtab_query', 'nlsep_answ', 'nlsep_label'],
    num_rows: 88116
})

In [135]:
dd = process_data.filter(lambda x: True if x['nlsep_answ']!='None' else False,num_proc=17)
dd

Filter (num_proc=17): 100%|██████████| 88116/88116 [00:00<00:00, 156255.01 examples/s]

Dataset({
    features: ['id', 'statement', 'label', 'table_caption', 'table_text', 'pandas_code', 'pandas_eval', 'nlsep_query', 'semtab_query', 'nlsep_answ', 'nlsep_label'],
    num_rows: 88007
})

In [136]:
dd = process_data.filter(lambda x: True if x['nlsep_label']!='None' else False,num_proc=17)
dd

Filter (num_proc=17): 100%|██████████| 88116/88116 [00:00<00:00, 162598.23 examples/s]

Dataset({
    features: ['id', 'statement', 'label', 'table_caption', 'table_text', 'pandas_code', 'pandas_eval', 'nlsep_query', 'semtab_query', 'nlsep_answ', 'nlsep_label'],
    num_rows: 59619
})

In [137]:
dd.shape[0]/process_data.shape[0]*100

67.65967588179218

In [139]:
true = dd.filter(lambda x : True if x['nlsep_label']==str(bool(x['label'])) else False,num_proc=17)

Filter (num_proc=17): 100%|██████████| 59619/59619 [00:00<00:00, 99274.44 examples/s]

In [140]:
true.shape[0]/dd.shape[0]*100

62.41298914775491

In [141]:
true.shape[0]/process_data.shape[0]*100

42.228426165509106

In [150]:
process_data = load_from_disk('answer_gen_proto_none_filtered_new_dataset/')
process_data

Dataset({
    features: ['id', 'statement', 'label', 'table_caption', 'table_text', 'pandas_code', 'pandas_eval', 'nlsep_query', 'semtab_query', 'proto_query', 'proto_answ', 'proto_label'],
    num_rows: 88116
})

In [151]:
dd = process_data.filter(lambda x: True if x['proto_answ']!='None' else False,num_proc=17)
dd

Dataset({
    features: ['id', 'statement', 'label', 'table_caption', 'table_text', 'pandas_code', 'pandas_eval', 'nlsep_query', 'semtab_query', 'proto_query', 'proto_answ', 'proto_label'],
    num_rows: 88065
})

In [152]:
dd = process_data.filter(lambda x: True if x['proto_label']!='None' else False,num_proc=17)
dd

Dataset({
    features: ['id', 'statement', 'label', 'table_caption', 'table_text', 'pandas_code', 'pandas_eval', 'nlsep_query', 'semtab_query', 'proto_query', 'proto_answ', 'proto_label'],
    num_rows: 46593
})

In [153]:
dd.shape[0]/process_data.shape[0]*100

52.876889554677916

In [154]:
true = dd.filter(lambda x : True if x['proto_label']==str(bool(x['label'])) else False,num_proc=17)

In [155]:
true.shape[0]/process_data.shape[0]*100

31.886377048436152

In [131]:
true.shape[0]/dd.shape[0]*100

58.11939624588789

In [156]:
process_data = load_from_disk('./tab_fact_test_xml_semtab/')
print(process_data)
dd = process_data.filter(lambda x: True if x['semtab_answ']!='None' else False,num_proc=17)
print(dd)
dd = process_data.filter(lambda x: True if x['semtab_label']!='None' else False,num_proc=17)
print(dd)
print(dd.shape[0]/process_data.shape[0]*100)
true = dd.filter(lambda x : True if x['semtab_label']==str(bool(x['label'])) else False,num_proc=17)
print(true.shape[0]/process_data.shape[0]*100)

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'semtab_answ', 'semtab_label'],
    num_rows: 12779
})

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:00<00:00, 28116.82 examples/s]

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'semtab_answ', 'semtab_label'],
    num_rows: 12779
})

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:00<00:00, 28618.56 examples/s]

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'semtab_answ', 'semtab_label'],
    num_rows: 8858
})
69.316847953674

Filter (num_proc=17): 100%|██████████| 8858/8858 [00:00<00:00, 18089.66 examples/s]

40.636982549495265

In [160]:
process_data = load_from_disk('./tab_fact_test_xml_nlsep/')
print(process_data)
dd = process_data.filter(lambda x: True if x['nlsep_answ']!='None' else False,num_proc=17)
print(dd)
dd = process_data.filter(lambda x: True if x['nlsep_label']!='None' else False,num_proc=17)
print(dd)
print(dd.shape[0]/process_data.shape[0]*100)
true = dd.filter(lambda x : True if x['nlsep_label']==str(bool(x['label'])) else False,num_proc=17)
print(true.shape[0]/process_data.shape[0]*100)

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'nlsep_answ', 'nlsep_label'],
    num_rows: 12779
})
Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'nlsep_answ', 'nlsep_label'],
    num_rows: 12779
})
Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'nlsep_answ', 'nlsep_label'],
    num_rows: 8522
})
66.68753423585571
41.341263009625166

In [161]:
dont_run = process_data.filter(lambda x: True if x['nlsep_label']=='None' else False,num_proc=17)

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:00<00:00, 27883.23 examples/s]

In [162]:
dont_run

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'nlsep_answ', 'nlsep_label'],
    num_rows: 4257
})

In [ ]:
from functools import partial
dont_run_correcting = dont_run.map(partial(dataset_processing,query_field='nlsep',system_correcting_prompt=system_correcting_prompt,
                                           system_prompt=system_prompt),num_proc=16)

Map (num_proc=16):   0%|          | 0/4257 [00:00<?, ? examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5


Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5


EEEERRRRRRR 625
'money raised'

Map (num_proc=16):   0%|          | 1/4257 [00:01<1:25:02,  1.20s/ examples]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR EEEERRRRRRR75
706can't multiply sequence by non-int of type 'float'

The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRR 880
leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1538
Can only use .dt accessor with datetimelike values

Map (num_proc=16):   0%|          | 3/4257 [00:01<36:14,  1.96 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   0%|          | 4/4257 [00:01<27:44,  2.56 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR

Map (num_proc=16):   0%|          | 6/4257 [00:02<18:35,  3.81 examples/s]

 0
The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1054
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   0%|          | 7/4257 [00:02<24:28,  2.89 examples/s]

EEEERRRRRRR 789
cannot do positional indexing on RangeIndex with these indexers [nan] of type float
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 148
The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   0%|          | 9/4257 [00:03<21:58,  3.22 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callableEEEERRRRRRR
 229
Can only compare identically-labeled Series objects

Map (num_proc=16):   0%|          | 11/4257 [00:03<20:42,  3.42 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

EEEERRRRRRR 1390
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR

Map (num_proc=16):   0%|          | 12/4257 [00:04<26:34,  2.66 examples/s]

308
Can only use .dt accessor with datetimelike values
EEEERRRRRRR 625
"['2q'] not in index"
'brazil scorers'Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

'str' object is not callable
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRREEEERRRRRRR  0
1226
'participant'Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 76
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRR 550
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callableGenerating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   0%|          | 16/4257 [00:05<23:28,  3.01 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   0%|          | 17/4257 [00:05<21:34,  3.27 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   0%|          | 18/4257 [00:06<20:32,  3.44 examples/s]

EEEERRRRRRR 1538
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 472
unterminated string literal (detected at line 1) (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   0%|          | 20/4257 [00:06<19:55,  3.55 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   0%|          | 21/4257 [00:06<18:00,  3.92 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 148
'numpy.int64' object has no attribute 'isin'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   1%|          | 22/4257 [00:07<22:06,  3.19 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   1%|          | 24/4257 [00:07<15:22,  4.59 examples/s]

EEEERRRRRRR 880
single positional indexer is out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   1%|          | 25/4257 [00:07<20:30,  3.44 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   1%|          | 26/4257 [00:08<18:08,  3.89 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   1%|          | 28/4257 [00:08<12:40,  5.56 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1056
'score'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'

Map (num_proc=16):   1%|          | 30/4257 [00:08<09:59,  7.05 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5'str' object is not callable

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 790
'best row 1'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   1%|          | 32/4257 [00:08<08:53,  7.92 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1390
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   1%|          | 34/4257 [00:09<11:56,  5.89 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 550
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   1%|          | 35/4257 [00:09<14:14,  4.94 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 395
invalid literal for int() with base 10: 'fernandez '

Map (num_proc=16):   1%|          | 36/4257 [00:09<14:45,  4.77 examples/s]

EEEERRRRRRR 231
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 76
Can only compare identically-labeled Series objects
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 625
'2q | loans received , 2q'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1539
'age'
'brazil scorers'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5'str' object is not callable

Map (num_proc=16):   1%|          | 37/4257 [00:10<22:28,  3.13 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   1%|          | 38/4257 [00:10<22:00,  3.20 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRRGenerating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
308
invalid literal for int() with base 10: ' 3 (11)'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   1%|          | 40/4257 [00:10<16:29,  4.26 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   1%|          | 42/4257 [00:11<14:19,  4.90 examples/s]

EEEERRRRRRR 472
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1227
single positional indexer is out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   1%|          | 43/4257 [00:11<20:43,  3.39 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 706
'p 2008'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   1%|          | 44/4257 [00:12<20:48,  3.38 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   1%|          | 45/4257 [00:12<19:33,  3.59 examples/s]

'brazil scorers'
'str' object is not callable
'brazil scorers'Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   1%|          | 48/4257 [00:12<12:59,  5.40 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   1%|          | 50/4257 [00:12<10:10,  6.90 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   1%|          | 52/4257 [00:12<08:18,  8.44 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 790
'best row 1'
EEEERRRRRRR 1390
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   1%|▏         | 54/4257 [00:13<11:59,  5.85 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1539
'age'
EEEERRRRRRR 76
Can only compare identically-labeled Series objects
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   1%|▏         | 55/4257 [00:14<16:51,  4.15 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 881
index 0 is out of bounds for axis 0 with size 0
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 149
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Map (num_proc=16):   1%|▏         | 56/4257 [00:14<18:55,  3.70 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   1%|▏         | 57/4257 [00:14<16:56,  4.13 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   1%|▏         | 58/4257 [00:14<19:37,  3.57 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   1%|▏         | 60/4257 [00:15<13:56,  5.02 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   1%|▏         | 62/4257 [00:15<16:00,  4.37 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 396
Can only use .dt accessor with datetimelike values
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   1%|▏         | 63/4257 [00:15<15:20,  4.56 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable'brazil scorers'

'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 231
single positional indexer is out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   2%|▏         | 67/4257 [00:16<09:43,  7.18 examples/s]

EEEERRRRRRR 309
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 551
'>' not supported between instances of 'str' and 'float'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 472
'retired'
EEEERRRRRRR 625
'money raised'
EEEERRRRRRR 1390
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   2%|▏         | 68/4257 [00:17<19:28,  3.59 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1539
'>' not supported between instances of 'str' and 'int'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   2%|▏         | 70/4257 [00:17<14:54,  4.68 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   2%|▏         | 71/4257 [00:18<22:10,  3.15 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   2%|▏         | 72/4257 [00:18<19:42,  3.54 examples/s]

EEEERRRRRRR 790
'best row 1'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1060
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Map (num_proc=16):   2%|▏         | 73/4257 [00:18<20:18,  3.43 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 706
'p 2008'

Map (num_proc=16):   2%|▏         | 74/4257 [00:18<18:29,  3.77 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   2%|▏         | 75/4257 [00:18<17:15,  4.04 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1391
could not convert string to float: '15.14 (104)'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   2%|▏         | 76/4257 [00:19<21:43,  3.21 examples/s]

'brazil scorers'
'str' object is not callable
EEEERRRRRRR 149
could not convert string to float: '19.8 (122)'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   2%|▏         | 78/4257 [00:19<17:39,  3.94 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   2%|▏         | 79/4257 [00:19<16:17,  4.27 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   2%|▏         | 81/4257 [00:20<15:06,  4.61 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 551
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   2%|▏         | 84/4257 [00:20<09:41,  7.18 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   2%|▏         | 85/4257 [00:20<09:41,  7.17 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1228
single positional indexer is out-of-bounds
EEEERRRRRRR 4
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 77
'2001-04-14'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   2%|▏         | 86/4257 [00:21<22:22,  3.11 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   2%|▏         | 87/4257 [00:21<21:04,  3.30 examples/s]

EEEERRRRRRR 882
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   2%|▏         | 88/4257 [00:22<18:25,  3.77 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   2%|▏         | 89/4257 [00:22<15:30,  4.48 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   2%|▏         | 91/4257 [00:22<15:09,  4.58 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 473
'brice feillu ( fra )'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 628
'berlin'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 396
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 309
'col'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   2%|▏         | 93/4257 [00:23<25:19,  2.74 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   2%|▏         | 94/4257 [00:24<23:46,  2.92 examples/s]

'brazil scorers'
'str' object is not callableGenerating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   2%|▏         | 96/4257 [00:24<16:20,  4.24 examples/s]

'brazil scorers'
'str' object is not callableGenerating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   2%|▏         | 99/4257 [00:24<12:21,  5.61 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   2%|▏         | 100/4257 [00:24<11:50,  5.85 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1542
'DataFrame' object has no attribute 'gcm'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 77
unsupported operand type(s) for -: 'str' and 'str'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   2%|▏         | 101/4257 [00:25<15:57,  4.34 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 790
'best row 1'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   2%|▏         | 102/4257 [00:25<17:53,  3.87 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   2%|▏         | 104/4257 [00:25<12:17,  5.63 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 706
'p 2008'

<string>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

EEEERRRRRRR 1391
'<=' not supported between instances of 'str' and 'float'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   3%|▎         | 110/4257 [00:26<10:29,  6.59 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 4
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 149
unsupported operand type(s) for -: 'str' and 'str'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   3%|▎         | 111/4257 [00:27<15:53,  4.35 examples/s]

EEEERRRRRRR 1062
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR'brazil scorers'
 'str' object is not callable309

'str' object has no attribute 'month'

Map (num_proc=16):   3%|▎         | 112/4257 [00:27<16:49,  4.10 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 629
Can only compare identically-labeled Series objects
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   3%|▎         | 113/4257 [00:27<16:49,  4.10 examples/s]

EEEERRRRRRR 232
attempt to get argmax of an empty sequence
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 884
invalid syntax (<string>, line 0)
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   3%|▎         | 114/4257 [00:27<17:55,  3.85 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5'brazil scorers'

'str' object is not callable
EEEERRRRRRR 552
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   3%|▎         | 116/4257 [00:28<20:26,  3.38 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR EEEERRRRRRR790
77'best row 1'

'>' not supported between instances of 'str' and 'int'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1229
name 'datetime' is not defined
EEEERRRRRRR 396
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   3%|▎         | 118/4257 [00:29<21:46,  3.17 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   3%|▎         | 119/4257 [00:29<23:29,  2.94 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   3%|▎         | 121/4257 [00:30<17:30,  3.94 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   3%|▎         | 122/4257 [00:30<21:28,  3.21 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 149
unsupported operand type(s) for -: 'str' and 'str'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   3%|▎         | 123/4257 [00:30<21:49,  3.16 examples/s]

EEEERRRRRRR 474
unsupported operand type(s) for -: 'str' and 'str'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 5
Could not convert string '70 + 71 + 68 + 72 = 281' to numeric
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR'brazil scorers'
707'str' object is not callable

Map (num_proc=16):   3%|▎         | 124/4257 [00:31<22:27,  3.07 examples/s]

unsupported operand type(s) for -: 'str' and 'int'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

EEEERRRRRRR 1391
invalid syntax (<string>, line 0)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   3%|▎         | 125/4257 [00:31<24:03,  2.86 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   3%|▎         | 127/4257 [00:31<17:46,  3.87 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   3%|▎         | 128/4257 [00:32<15:24,  4.47 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 884
'amt 3.0'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   3%|▎         | 130/4257 [00:32<19:26,  3.54 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   3%|▎         | 132/4257 [00:33<15:10,  4.53 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'

Map (num_proc=16):   3%|▎         | 133/4257 [00:33<13:50,  4.97 examples/s]

'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   3%|▎         | 136/4257 [00:33<09:27,  7.26 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   3%|▎         | 138/4257 [00:33<09:40,  7.10 examples/s]

EEEERRRRRRR 552
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   3%|▎         | 140/4257 [00:33<07:50,  8.76 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 790
'best row 1'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1391
unsupported operand type(s) for &: 'str' and 'bool'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   3%|▎         | 142/4257 [00:34<14:59,  4.58 examples/s]

EEEERRRRRRR 1542
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 309Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

unsupported operand type(s) for -: 'str' and 'str'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   3%|▎         | 143/4257 [00:35<17:07,  4.01 examples/s]

EEEERRRRRRR 1230
invalid syntax (<string>, line 0)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   3%|▎         | 144/4257 [00:35<15:31,  4.42 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   3%|▎         | 146/4257 [00:35<13:10,  5.20 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 149
'<' not supported between instances of 'str' and 'int'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   3%|▎         | 147/4257 [00:35<16:20,  4.19 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 77
Can only use .dt accessor with datetimelike values
EEEERRRRRRR 629
'event'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   3%|▎         | 148/4257 [00:36<20:28,  3.35 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 234
int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   4%|▎         | 149/4257 [00:36<20:31,  3.34 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1066
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   4%|▎         | 151/4257 [00:37<16:39,  4.11 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   4%|▎         | 152/4257 [00:37<15:34,  4.39 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   4%|▎         | 154/4257 [00:37<14:53,  4.59 examples/s]

EEEERRRRRRR 474
unsupported operand type(s) for -: 'str' and 'str'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 790
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   4%|▎         | 155/4257 [00:38<21:46,  3.14 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   4%|▎         | 156/4257 [00:38<19:38,  3.48 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   4%|▎         | 159/4257 [00:38<12:57,  5.27 examples/s]

EEEERRRRRRR 397
unterminated string literal (detected at line 1) (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 151
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   4%|▍         | 161/4257 [00:39<18:31,  3.69 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   4%|▍         | 162/4257 [00:39<17:33,  3.89 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   4%|▍         | 163/4257 [00:39<16:00,  4.26 examples/s]

EEEERRRRRRR 1542
'>=' not supported between instances of 'str' and 'int'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   4%|▍         | 165/4257 [00:40<14:11,  4.81 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 709
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   4%|▍         | 167/4257 [00:40<16:44,  4.07 examples/s]

EEEERRRRRRR 1066
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   4%|▍         | 168/4257 [00:41<17:53,  3.81 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

'brazil scorers'
'str' object is not callable

Map (num_proc=16):   4%|▍         | 170/4257 [00:41<15:05,  4.51 examples/s]

EEEERRRRRRR 1230
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 552
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   4%|▍         | 171/4257 [00:42<18:10,  3.75 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   4%|▍         | 173/4257 [00:42<13:24,  5.08 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 5
name 'average_score' is not defined
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   4%|▍         | 174/4257 [00:42<14:46,  4.61 examples/s]

EEEERRRRRRR 888
The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRR 309
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5unsupported operand type(s) for -: 'str' and 'str'

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'EEEERRRRRRR
 'str' object is not callable397

Map (num_proc=16):   4%|▍         | 176/4257 [00:42<14:31,  4.68 examples/s]

The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   4%|▍         | 177/4257 [00:43<14:40,  4.64 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   4%|▍         | 178/4257 [00:43<17:26,  3.90 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   4%|▍         | 179/4257 [00:43<15:20,  4.43 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR

Map (num_proc=16):   4%|▍         | 180/4257 [00:43<13:30,  5.03 examples/s]

 790
'best row 1'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   4%|▍         | 181/4257 [00:44<16:17,  4.17 examples/s]

EEEERRRRRRR 234
Can only compare identically-labeled Series objects
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   4%|▍         | 182/4257 [00:44<16:47,  4.05 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   4%|▍         | 183/4257 [00:44<17:04,  3.98 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   4%|▍         | 184/4257 [00:44<15:01,  4.52 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   4%|▍         | 185/4257 [00:44<14:57,  4.54 examples/s]

EEEERRRRRRR 631
invalid literal for int() with base 10: 'w 14'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   4%|▍         | 186/4257 [00:45<16:32,  4.10 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   4%|▍         | 187/4257 [00:45<15:47,  4.30 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1542
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   4%|▍         | 188/4257 [00:45<20:45,  3.27 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callableGenerating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   5%|▍         | 192/4257 [00:46<09:14,  7.33 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   5%|▍         | 194/4257 [00:46<15:34,  4.35 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 889
'director(s)'

Map (num_proc=16):   5%|▍         | 195/4257 [00:47<15:46,  4.29 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   5%|▍         | 197/4257 [00:47<11:54,  5.68 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   5%|▍         | 198/4257 [00:47<12:56,  5.23 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   5%|▍         | 200/4257 [00:47<12:01,  5.62 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   5%|▍         | 201/4257 [00:48<14:05,  4.80 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   5%|▍         | 202/4257 [00:48<12:26,  5.44 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   5%|▍         | 204/4257 [00:48<12:59,  5.20 examples/s]

EEEERRRRRRR 78
'grand slam tournaments'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 790
'best row 1'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 477
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Map (num_proc=16):   5%|▍         | 205/4257 [00:49<15:16,  4.42 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 6
closing parenthesis ']' does not match opening parenthesis '(' (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 151
unterminated string literal (detected at line 1) (<string>, line 1)
EEEERRRRRRR 397
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRRGenerating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
 631
'score'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1398
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   5%|▍         | 207/4257 [00:50<24:55,  2.71 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 552
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1068
unterminated string literal (detected at line 1) (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   5%|▍         | 208/4257 [00:51<30:36,  2.21 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   5%|▍         | 211/4257 [00:51<23:09,  2.91 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   5%|▍         | 212/4257 [00:51<21:45,  3.10 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 310
'minnesota'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   5%|▌         | 213/4257 [00:52<18:47,  3.59 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 711
unterminated string literal (detected at line 1) (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   5%|▌         | 214/4257 [00:52<18:51,  3.57 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   5%|▌         | 215/4257 [00:52<16:05,  4.19 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 78
'win - loss'
EEEERRRRRRR 235
'merja rantanen'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 889
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   5%|▌         | 217/4257 [00:53<22:23,  3.01 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   5%|▌         | 218/4257 [00:53<19:34,  3.44 examples/s]

EEEERRRRRRR 791
Can only use .dt accessor with datetimelike values
EEEERRRRRRR 151
'no'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1239
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRR 477
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   5%|▌         | 219/4257 [00:54<29:07,  2.31 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   5%|▌         | 220/4257 [00:54<23:53,  2.82 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1543
'McLaren M23'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   5%|▌         | 221/4257 [00:55<26:02,  2.58 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   5%|▌         | 224/4257 [00:55<16:51,  3.99 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   5%|▌         | 225/4257 [00:55<16:09,  4.16 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1069
'no'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   5%|▌         | 226/4257 [00:55<16:20,  4.11 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   5%|▌         | 228/4257 [00:56<13:50,  4.85 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 553
'designation'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   5%|▌         | 230/4257 [00:56<13:52,  4.84 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 6
Can only use .dt accessor with datetimelike values

Map (num_proc=16):   5%|▌         | 231/4257 [00:56<14:04,  4.76 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

EEEERRRRRRR 1239
'Series' object has no attribute 'vfl_club'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   5%|▌         | 233/4257 [00:57<14:57,  4.49 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 889
'director(s)'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 78
'year end ranking'

Map (num_proc=16):   6%|▌         | 235/4257 [00:57<14:20,  4.67 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   6%|▌         | 236/4257 [00:58<19:18,  3.47 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   6%|▌         | 238/4257 [00:58<15:03,  4.45 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR'brazil scorers'
398'str' object is not callable

Map (num_proc=16):   6%|▌         | 239/4257 [00:58<14:07,  4.74 examples/s]

'12-11'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   6%|▌         | 240/4257 [00:59<16:27,  4.07 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   6%|▌         | 242/4257 [00:59<11:25,  5.86 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 237
'>' not supported between instances of 'str' and 'int'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 312
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   6%|▌         | 243/4257 [00:59<19:56,  3.36 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   6%|▌         | 244/4257 [01:00<17:06,  3.91 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 711
can't multiply sequence by non-int of type 'float'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR

Map (num_proc=16):   6%|▌         | 245/4257 [01:00<21:36,  3.09 examples/s]

 152
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 631
Can only use .dt accessor with datetimelike values
'brazil scorers''brazil scorers'

'str' object is not callable'str' object is not callable

Map (num_proc=16):   6%|▌         | 246/4257 [01:00<20:13,  3.30 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   6%|▌         | 249/4257 [01:01<16:55,  3.95 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1545
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1401
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1239
'location of death'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 553
'designation'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   6%|▌         | 250/4257 [01:02<28:32,  2.34 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 477
'Timestamp' object has no attribute 'isna'

Map (num_proc=16):   6%|▌         | 251/4257 [01:03<32:29,  2.05 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1069
'no'
EEEERRRRRRR 78
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   6%|▌         | 252/4257 [01:03<31:40,  2.11 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   6%|▌         | 253/4257 [01:03<28:10,  2.37 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   6%|▌         | 254/4257 [01:04<27:38,  2.41 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   6%|▌         | 255/4257 [01:04<24:40,  2.70 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   6%|▌         | 256/4257 [01:04<22:17,  2.99 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   6%|▌         | 257/4257 [01:04<18:30,  3.60 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 312
single positional indexer is out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   6%|▌         | 259/4257 [01:05<15:05,  4.42 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   6%|▌         | 260/4257 [01:05<15:57,  4.17 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

EEEERRRRRRR 153
'int' object has no attribute 'sum'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   6%|▌         | 262/4257 [01:06<21:32,  3.09 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'EEEERRRRRRR
 1239'str' object is not callable
'new guinea host 9 vfl game'

Map (num_proc=16):   6%|▌         | 264/4257 [01:06<15:40,  4.24 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   6%|▋         | 267/4257 [01:07<12:56,  5.14 examples/s]

EEEERRRRRRR 792
Cannot perform 'rand_' with a dtyped [int64] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 6
Can only use .dt accessor with datetimelike values
'brazil scorers'EEEERRRRRRR
 'str' object is not callable398

single positional indexer is out-of-bounds

Map (num_proc=16):   6%|▋         | 268/4257 [01:07<14:45,  4.51 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 889
unterminated string literal (detected at line 1) (<string>, line 1)
EEEERRRRRRR 78
'Australian open'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 477
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRR 711
ufunc 'less_equal' did not contain a loop with signature matching types (<class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.StrDType'>) -> None
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 237
EEEERRRRRRR'2008-09 Real Madrid CF season'
1402
'loss'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 553
'designation'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1546
'lap-by-lap'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1070
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 631
invalid literal for int() with base 10: 'w'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   6%|▋         | 269/4257 [01:09<42:10,  1.58 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   6%|▋         | 270/4257 [01:09<34:39,  1.92 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   6%|▋         | 271/4257 [01:10<41:44,  1.59 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   6%|▋         | 272/4257 [01:11<38:52,  1.71 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   6%|▋         | 273/4257 [01:11<31:10,  2.13 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   6%|▋         | 276/4257 [01:11<16:05,  4.12 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   7%|▋         | 277/4257 [01:11<16:46,  3.96 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   7%|▋         | 278/4257 [01:12<16:07,  4.11 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   7%|▋         | 280/4257 [01:12<11:06,  5.97 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   7%|▋         | 282/4257 [01:12<10:21,  6.39 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1240
'samba / young hearts run free'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   7%|▋         | 283/4257 [01:13<16:49,  3.94 examples/s]

EEEERRRRRRR 312
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 711
single positional indexer is out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1073
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRR 157
name 'datetime' is not defined
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   7%|▋         | 285/4257 [01:13<19:41,  3.36 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   7%|▋         | 286/4257 [01:14<18:16,  3.62 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   7%|▋         | 287/4257 [01:14<15:50,  4.18 examples/s]

EEEERRRRRRR 632
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

EEEERRRRRRR 'brazil scorers'6

'str' object is not callableCan only use .dt accessor with datetimelike values

Map (num_proc=16):   7%|▋         | 288/4257 [01:14<17:31,  3.77 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1546
"['lap-by-lap'] not in index"
EEEERRRRRRR 479
invalid literal for int() with base 10: 'w 96'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   7%|▋         | 289/4257 [01:14<18:23,  3.60 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5EEEERRRRRRR
 237
'>=' not supported between instances of 'str' and 'int'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 553
'designation'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
EEEERRRRRRR

Map (num_proc=16):   7%|▋         | 290/4257 [01:16<36:46,  1.80 examples/s]

 890
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 793
unmatched ']' (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1405
no units specified
EEEERRRRRRR 78
invalid syntax (<string>, line 0)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   7%|▋         | 291/4257 [01:16<42:47,  1.54 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   7%|▋         | 292/4257 [01:17<33:34,  1.97 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   7%|▋         | 293/4257 [01:17<28:24,  2.33 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   7%|▋         | 295/4257 [01:17<21:15,  3.11 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   7%|▋         | 297/4257 [01:18<19:34,  3.37 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 634
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   7%|▋         | 298/4257 [01:18<21:22,  3.09 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   7%|▋         | 299/4257 [01:19<22:01,  3.00 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   7%|▋         | 300/4257 [01:19<22:34,  2.92 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 398
'Rattlers'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   7%|▋         | 303/4257 [01:19<15:27,  4.26 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   7%|▋         | 304/4257 [01:20<15:14,  4.32 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   7%|▋         | 305/4257 [01:20<16:22,  4.02 examples/s]

EEEERRRRRRR 712
single positional indexer is out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   7%|▋         | 307/4257 [01:20<11:25,  5.76 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1240
'samba / young hearts run free'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 314
'retired'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   7%|▋         | 308/4257 [01:21<19:48,  3.32 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   7%|▋         | 309/4257 [01:21<18:55,  3.48 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 157
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1549
'year'
EEEERRRRRRR 479
invalid literal for int() with base 10: 'w 96'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   7%|▋         | 310/4257 [01:22<24:23,  2.70 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1075
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Map (num_proc=16):   7%|▋         | 311/4257 [01:22<24:14,  2.71 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   7%|▋         | 312/4257 [01:22<22:37,  2.91 examples/s]

EEEERRRRRRR 793
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 553
'designation'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   7%|▋         | 313/4257 [01:23<26:32,  2.48 examples/s]

'brazil scorers''brazil scorers'

'str' object is not callable'str' object is not callable

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   7%|▋         | 316/4257 [01:23<16:49,  3.90 examples/s]

EEEERRRRRRR 6
'str' object has no attribute 'str'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1405
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   7%|▋         | 317/4257 [01:24<24:31,  2.68 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   7%|▋         | 319/4257 [01:24<19:29,  3.37 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   8%|▊         | 320/4257 [01:24<16:49,  3.90 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   8%|▊         | 321/4257 [01:25<16:56,  3.87 examples/s]

EEEERRRRRRR 892
invalid literal for int() with base 10: '68 + 68 + 71 = 207'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 314
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Map (num_proc=16):   8%|▊         | 322/4257 [01:25<19:08,  3.43 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 78
'>=' not supported between instances of 'str' and 'int'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   8%|▊         | 323/4257 [01:25<19:58,  3.28 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   8%|▊         | 324/4257 [01:26<17:45,  3.69 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   8%|▊         | 325/4257 [01:26<17:08,  3.82 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   8%|▊         | 326/4257 [01:26<16:19,  4.01 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 237
'ends row'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   8%|▊         | 327/4257 [01:26<19:23,  3.38 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   8%|▊         | 328/4257 [01:27<17:26,  3.75 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   8%|▊         | 330/4257 [01:27<13:15,  4.94 examples/s]

EEEERRRRRRR 634
'<' not supported between instances of 'str' and 'int'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 712
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 399
single positional indexer is out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   8%|▊         | 332/4257 [01:28<22:19,  2.93 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   8%|▊         | 334/4257 [01:28<17:41,  3.69 examples/s]

'brazil scorers'
'str' object is not callable
EEEERRRRRRR 157
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   8%|▊         | 336/4257 [01:28<12:58,  5.04 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1243
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
EEEERRRRRRR EEEERRRRRRR1077
554The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

'club team'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   8%|▊         | 337/4257 [01:29<15:47,  4.14 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   8%|▊         | 338/4257 [01:29<18:15,  3.58 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   8%|▊         | 340/4257 [01:30<16:58,  3.85 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   8%|▊         | 341/4257 [01:30<17:44,  3.68 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1550
'best row 1'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   8%|▊         | 342/4257 [01:31<23:58,  2.72 examples/s]

EEEERRRRRRR 237
'>=' not supported between instances of 'str' and 'int'
EEEERRRRRRR 1407
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   8%|▊         | 343/4257 [01:31<27:32,  2.37 examples/s]

EEEERRRRRRR 479
invalid literal for int() with base 10: 'w 96'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 712
single positional indexer is out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   8%|▊         | 345/4257 [01:32<21:48,  2.99 examples/s]

'brazil scorers'
'str' object is not callable
'brazil scorers'Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   8%|▊         | 349/4257 [01:32<13:53,  4.69 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   8%|▊         | 350/4257 [01:32<13:45,  4.73 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   8%|▊         | 352/4257 [01:33<12:40,  5.13 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   8%|▊         | 353/4257 [01:33<12:27,  5.23 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   8%|▊         | 355/4257 [01:33<11:56,  5.45 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 634
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable'brazil scorers'

Map (num_proc=16):   8%|▊         | 356/4257 [01:34<14:29,  4.49 examples/s]

'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 554
'club team'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   8%|▊         | 358/4257 [01:34<14:20,  4.53 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   8%|▊         | 361/4257 [01:34<09:07,  7.11 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 793
0
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'EEEERRRRRRR
 'str' object is not callable1077

The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Map (num_proc=16):   9%|▊         | 363/4257 [01:35<14:13,  4.56 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   9%|▊         | 366/4257 [01:35<12:11,  5.32 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   9%|▊         | 368/4257 [01:36<12:03,  5.38 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   9%|▊         | 371/4257 [01:36<11:55,  5.43 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1407
unterminated string literal (detected at line 1) (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   9%|▉         | 373/4257 [01:37<12:07,  5.34 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 78
'year end ranking'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   9%|▉         | 374/4257 [01:37<15:03,  4.30 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   9%|▉         | 375/4257 [01:37<14:26,  4.48 examples/s]

EEEERRRRRRR 479
invalid literal for int() with base 10: 'w 96'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   9%|▉         | 380/4257 [01:38<09:18,  6.94 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   9%|▉         | 381/4257 [01:38<11:09,  5.79 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   9%|▉         | 382/4257 [01:38<10:30,  6.14 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 554
'team'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   9%|▉         | 383/4257 [01:39<12:24,  5.20 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 157
The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 634
could not convert string to float: '17.20 (122)'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   9%|▉         | 384/4257 [01:39<15:58,  4.04 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 315
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   9%|▉         | 385/4257 [01:39<19:16,  3.35 examples/s]

EEEERRRRRRR 8
The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   9%|▉         | 386/4257 [01:40<19:07,  3.37 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 895
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Map (num_proc=16):   9%|▉         | 387/4257 [01:40<19:13,  3.36 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   9%|▉         | 390/4257 [01:41<15:26,  4.17 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1245
invalid literal for int() with base 10: ' 3 ot'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 713
'no'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   9%|▉         | 391/4257 [01:41<16:52,  3.82 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   9%|▉         | 392/4257 [01:41<17:25,  3.70 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   9%|▉         | 394/4257 [01:42<13:58,  4.61 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   9%|▉         | 395/4257 [01:42<13:06,  4.91 examples/s]

EEEERRRRRRR 1554Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

"'rating'"
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   9%|▉         | 396/4257 [01:42<17:12,  3.74 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
EEEERRRRRRR'str' object is not callable 794

Map (num_proc=16):   9%|▉         | 397/4257 [01:43<23:56,  2.69 examples/s]

unsupported operand type(s) for -: 'str' and 'str'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 402
'best row 1'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR EEEERRRRRRR554
238'DataFrame' object has no attribute 'college'

<lambda>() got an unexpected keyword argument 'axis'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   9%|▉         | 398/4257 [01:43<23:35,  2.73 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   9%|▉         | 399/4257 [01:43<20:21,  3.16 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   9%|▉         | 401/4257 [01:44<16:29,  3.90 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 479
'location'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):   9%|▉         | 403/4257 [01:44<13:27,  4.78 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 9
'attendance'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):   9%|▉         | 404/4257 [01:45<20:29,  3.13 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  10%|▉         | 405/4257 [01:45<21:48,  2.94 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 78
unterminated string literal (detected at line 1) (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  10%|▉         | 407/4257 [01:46<17:57,  3.57 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  10%|▉         | 409/4257 [01:46<14:44,  4.35 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1554
could not convert string to float: 'viewers'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 713
'[7, 8] not in index'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  10%|▉         | 411/4257 [01:46<16:45,  3.83 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers''brazil scorers'

'str' object is not callable'str' object is not callable

Map (num_proc=16):  10%|▉         | 412/4257 [01:47<17:55,  3.57 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5EEEERRRRRRR
 1407
'no'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  10%|▉         | 415/4257 [01:47<13:27,  4.76 examples/s]

'brazil scorers'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5'str' object is not callable

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  10%|▉         | 417/4257 [01:47<12:00,  5.33 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 402
'best row 1'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  10%|▉         | 418/4257 [01:48<11:24,  5.61 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1081
'retired'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 9
'location'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  10%|▉         | 419/4257 [01:49<22:12,  2.88 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  10%|▉         | 420/4257 [01:49<19:40,  3.25 examples/s]

EEEERRRRRRR 479
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRR 896
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 159
Can only use .dt accessor with datetimelike values'brazil scorers'

Map (num_proc=16):  10%|▉         | 421/4257 [01:49<21:39,  2.95 examples/s]

'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  10%|▉         | 423/4257 [01:49<15:14,  4.19 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  10%|▉         | 424/4257 [01:50<17:13,  3.71 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1245
invalid literal for int() with base 10: ' 3 ot'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 636
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  10%|▉         | 425/4257 [01:51<25:23,  2.51 examples/s]

EEEERRRRRRR 238
unterminated string literal (detected at line 1) (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 794
unsupported operand type(s) for -: 'str' and 'str'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1554
'>' not supported between instances of 'str' and 'float'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 'brazil scorers'555

'str' object is not callable'name'

Map (num_proc=16):  10%|█         | 426/4257 [01:51<29:01,  2.20 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  10%|█         | 427/4257 [01:52<31:39,  2.02 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 'brazil scorers'402

'str' object is not callable"['best row 1'] not in index"

Map (num_proc=16):  10%|█         | 428/4257 [01:52<30:34,  2.09 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  10%|█         | 429/4257 [01:53<30:10,  2.11 examples/s]

EEEERRRRRRR 315
invalid syntax (<string>, line 0)
EEEERRRRRRR 1082
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 713
'no'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  10%|█         | 430/4257 [01:53<32:06,  1.99 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  10%|█         | 431/4257 [01:53<27:00,  2.36 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  10%|█         | 432/4257 [01:54<26:03,  2.45 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 898
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 79
list index out of range
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  10%|█         | 433/4257 [01:54<25:50,  2.47 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  10%|█         | 435/4257 [01:55<21:48,  2.92 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  10%|█         | 438/4257 [01:55<12:45,  4.99 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  10%|█         | 439/4257 [01:55<12:00,  5.30 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  10%|█         | 440/4257 [01:55<13:30,  4.71 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1407
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  10%|█         | 441/4257 [01:56<16:57,  3.75 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 159
can only concatenate str (not "Timedelta") to str
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  10%|█         | 442/4257 [01:56<19:01,  3.34 examples/s]

EEEERRRRRRR 636
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRR 795
unterminated string literal (detected at line 1) (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  10%|█         | 443/4257 [01:57<21:08,  3.01 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  10%|█         | 445/4257 [01:57<13:47,  4.61 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█         | 447/4257 [01:57<13:01,  4.87 examples/s]

EEEERRRRRRR 1246
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 9
'location'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█         | 448/4257 [01:58<17:29,  3.63 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1554
'>=' not supported between instances of 'str' and 'int'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 713
name 'datetime' is not defined

Map (num_proc=16):  11%|█         | 449/4257 [01:58<19:16,  3.29 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 79
invalid literal for int() with base 10: 'loss'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 402
'best row 1'
EEEERRRRRRR 1082
'>' not supported between instances of 'str' and 'int'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 238
unsupported operand type(s) for -: 'str' and 'str'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█         | 450/4257 [01:59<30:44,  2.06 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 315
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█         | 451/4257 [02:00<29:25,  2.16 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  11%|█         | 452/4257 [02:00<26:25,  2.40 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█         | 453/4257 [02:00<21:58,  2.88 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█         | 454/4257 [02:00<19:13,  3.30 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1554
'>' not supported between instances of 'str' and 'float'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 899
'international tourist arrivals (2010)'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 795
unterminated string literal (detected at line 1) (<string>, line 1)
EEEERRRRRRR 9
'location'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

EEEERRRRRRR 555
'name'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1407
'>' not supported between instances of 'str' and 'float'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█         | 455/4257 [02:02<48:42,  1.30 examples/s]

EEEERRRRRRR 481
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█         | 456/4257 [02:03<42:33,  1.49 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█         | 458/4257 [02:03<24:43,  2.56 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█         | 459/4257 [02:03<24:33,  2.58 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█         | 460/4257 [02:03<22:37,  2.80 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█         | 461/4257 [02:04<20:29,  3.09 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 79
'result'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█         | 462/4257 [02:04<22:05,  2.86 examples/s]

EEEERRRRRRR 1247
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█         | 463/4257 [02:04<17:57,  3.52 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers''brazil scorers'

'str' object is not callable'str' object is not callable

Map (num_proc=16):  11%|█         | 464/4257 [02:04<15:15,  4.14 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 402
'best row 2'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█         | 466/4257 [02:05<16:03,  3.93 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 9
'location'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█         | 467/4257 [02:05<18:29,  3.42 examples/s]

EEEERRRRRRR 636
The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1085
'atp masters series'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█         | 468/4257 [02:06<28:01,  2.25 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR'brazil scorers'
795'str' object is not callable

invalid syntax. Perhaps you forgot a comma? (<string>, line 1)
EEEERRRRRRR 1407
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 159
'[' was never closed (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR

Map (num_proc=16):  11%|█         | 470/4257 [02:07<24:46,  2.55 examples/s]

1555
unterminated string literal (detected at line 1) (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 900
'year'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█         | 471/4257 [02:07<31:10,  2.02 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█         | 472/4257 [02:08<27:28,  2.30 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 713
positional indexers are out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  11%|█         | 474/4257 [02:09<27:51,  2.26 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 9
'attendance'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers''brazil scorers'

'str' object is not callable'str' object is not callable

Map (num_proc=16):  11%|█         | 475/4257 [02:09<29:40,  2.12 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 241
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
EEEERRRRRRR 1247
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█         | 478/4257 [02:10<19:40,  3.20 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█▏        | 479/4257 [02:10<19:59,  3.15 examples/s]

EEEERRRRRRR 316
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█▏        | 480/4257 [02:10<17:16,  3.64 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█▏        | 481/4257 [02:10<17:55,  3.51 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5EEEERRRRRRR
 555
'date died'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1085
'annual win - loss'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  11%|█▏        | 482/4257 [02:11<22:42,  2.77 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 79
invalid literal for int() with base 10: 'loss'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 795
invalid syntax. Perhaps you forgot a comma? (<string>, line 1)
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█▏        | 483/4257 [02:12<25:15,  2.49 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█▏        | 484/4257 [02:12<25:49,  2.43 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 636
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 482
nothing to repeat at position 0
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR EEEERRRRRRR9
901'location'

Cannot perform 'rand_' with a dtyped [bool] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█▏        | 486/4257 [02:13<30:43,  2.05 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  11%|█▏        | 487/4257 [02:13<28:12,  2.23 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 402
'best row 1'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  11%|█▏        | 489/4257 [02:14<24:58,  2.51 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  12%|█▏        | 490/4257 [02:15<25:18,  2.48 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  12%|█▏        | 492/4257 [02:15<19:40,  3.19 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  12%|█▏        | 493/4257 [02:15<17:19,  3.62 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1558
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRR 1085
'annual win - loss'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 9
single positional indexer is out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  12%|█▏        | 495/4257 [02:16<22:42,  2.76 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  12%|█▏        | 496/4257 [02:16<21:51,  2.87 examples/s]

EEEERRRRRRR 79
invalid literal for int() with base 10: 'loss'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callableGenerating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  12%|█▏        | 499/4257 [02:17<16:43,  3.75 examples/s]

EEEERRRRRRR 1409
invalid syntax (<string>, line 0)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 159
invalid literal for int() with base 10: ''
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  12%|█▏        | 500/4257 [02:17<19:19,  3.24 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  12%|█▏        | 502/4257 [02:18<17:58,  3.48 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1249
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRR 795
unterminated string literal (detected at line 1) (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 636
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  12%|█▏        | 503/4257 [02:19<26:35,  2.35 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  12%|█▏        | 505/4257 [02:19<20:19,  3.08 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  12%|█▏        | 507/4257 [02:19<15:17,  4.09 examples/s]

EEEERRRRRRR 317
'winner'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  12%|█▏        | 508/4257 [02:20<15:50,  3.94 examples/s]

EEEERRRRRRR 1088
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  12%|█▏        | 510/4257 [02:20<13:35,  4.60 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 716
'col'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 79
'str' object has no attribute 'min'
EEEERRRRRRR 9
'location'
EEEERRRRRRR 901
'attendance'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 482
nothing to repeat at position 0

Map (num_proc=16):  12%|█▏        | 511/4257 [02:21<28:38,  2.18 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  12%|█▏        | 512/4257 [02:22<27:52,  2.24 examples/s]

'brazil scorers'EEEERRRRRRR
 'str' object is not callable243

The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  12%|█▏        | 514/4257 [02:22<26:19,  2.37 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR EEEERRRRRRR402
1249'best row 1'

The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  12%|█▏        | 515/4257 [02:23<27:59,  2.23 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  12%|█▏        | 516/4257 [02:23<23:39,  2.64 examples/s]

EEEERRRRRRR 1558
invalid syntax (<string>, line 0)
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 9
'location'
EEEERRRRRRR 1409
'location'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 160
'numpy.int64' object has no attribute 'equals'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 555
invalid syntax (<string>, line 0)
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  12%|█▏        | 518/4257 [02:25<34:17,  1.82 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  12%|█▏        | 519/4257 [02:25<30:50,  2.02 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  12%|█▏        | 520/4257 [02:25<26:36,  2.34 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 317
invalid syntax. Perhaps you forgot a comma? (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 636
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  12%|█▏        | 521/4257 [02:26<37:09,  1.68 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 716
'col'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  12%|█▏        | 522/4257 [02:27<31:09,  2.00 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  12%|█▏        | 523/4257 [02:27<24:16,  2.56 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 243
Cannot perform 'rand_' with a dtyped [bool] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 795
invalid syntax. Perhaps you forgot a comma? (<string>, line 1)
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  12%|█▏        | 525/4257 [02:27<20:58,  2.97 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers''brazil scorers'

'str' object is not callable'str' object is not callable

Map (num_proc=16):  12%|█▏        | 526/4257 [02:28<20:35,  3.02 examples/s]

EEEERRRRRRR 161
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5'brazil scorers'

'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  12%|█▏        | 529/4257 [02:28<16:33,  3.75 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  12%|█▏        | 531/4257 [02:29<14:45,  4.21 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1558
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 79
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  12%|█▏        | 532/4257 [02:29<20:32,  3.02 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  13%|█▎        | 533/4257 [02:30<20:37,  3.01 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  13%|█▎        | 535/4257 [02:30<15:53,  3.90 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  13%|█▎        | 536/4257 [02:30<15:38,  3.97 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR'brazil scorers'
243'str' object is not callable

The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Map (num_proc=16):  13%|█▎        | 538/4257 [02:31<14:16,  4.34 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 555
'name'
EEEERRRRRRR 483
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRR 1249
can only concatenate str (not "int") to str
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  13%|█▎        | 539/4257 [02:31<20:40,  3.00 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 903
invalid literal for int() with base 10: 'w 112 '
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  13%|█▎        | 540/4257 [02:32<22:13,  2.79 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 402

Map (num_proc=16):  13%|█▎        | 542/4257 [02:32<16:26,  3.77 examples/s]

'best row 1'
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR

Map (num_proc=16):  13%|█▎        | 544/4257 [02:32<16:42,  3.70 examples/s]

 1410
invalid syntax (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  13%|█▎        | 545/4257 [02:33<17:17,  3.58 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  13%|█▎        | 546/4257 [02:33<18:51,  3.28 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 161EEEERRRRRRR
 The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().11

Can only compare identically-labeled Series objects
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1560
invalid literal for int() with base 10: 'w'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 716
'city'
EEEERRRRRRREEEERRRRRRR  636317

Can only use .dt accessor with datetimelike valuesunterminated string literal (detected at line 1) (<string>, line 1)

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  13%|█▎        | 547/4257 [02:34<33:41,  1.84 examples/s]

EEEERRRRRRR 1093
'engine'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  13%|█▎        | 548/4257 [02:35<27:34,  2.24 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  13%|█▎        | 550/4257 [02:35<22:10,  2.79 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  13%|█▎        | 551/4257 [02:35<20:51,  2.96 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  13%|█▎        | 552/4257 [02:36<20:06,  3.07 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 795
unterminated string literal (detected at line 1) (<string>, line 1)
EEEERRRRRRR 80
invalid literal for int() with base 10: 'pepsi center 15823'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1249
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  13%|█▎        | 553/4257 [02:37<36:38,  1.68 examples/s]

EEEERRRRRRR 402
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  13%|█▎        | 554/4257 [02:37<31:56,  1.93 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  13%|█▎        | 555/4257 [02:38<31:38,  1.95 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  13%|█▎        | 556/4257 [02:38<25:16,  2.44 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers''brazil scorers'

'str' object is not callable'str' object is not callable

Map (num_proc=16):  13%|█▎        | 559/4257 [02:38<13:01,  4.73 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  13%|█▎        | 561/4257 [02:39<13:20,  4.62 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  13%|█▎        | 562/4257 [02:39<15:24,  4.00 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  13%|█▎        | 563/4257 [02:39<17:25,  3.53 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 555
'dates'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  13%|█▎        | 565/4257 [02:40<12:44,  4.83 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 483
'<' not supported between instances of 'str' and 'int'
EEEERRRRRRR 163
unsupported operand type(s) for -: 'str' and 'int'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  13%|█▎        | 566/4257 [02:40<14:22,  4.28 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1096
'no'

Map (num_proc=16):  13%|█▎        | 567/4257 [02:40<14:31,  4.24 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  13%|█▎        | 568/4257 [02:40<14:09,  4.34 examples/s]

EEEERRRRRRR 903
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRR 795
unmatched ')' (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 318
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 244
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRR 1249
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  13%|█▎        | 570/4257 [02:41<20:50,  2.95 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  13%|█▎        | 572/4257 [02:42<17:19,  3.55 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 80
invalid literal for int() with base 10: 'pepsi center 15823'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  13%|█▎        | 573/4257 [02:42<20:14,  3.03 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 716
'city'
EEEERRRRRRR 1562
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  13%|█▎        | 574/4257 [02:43<24:26,  2.51 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  14%|█▎        | 575/4257 [02:43<21:33,  2.85 examples/s]

EEEERRRRRRR 403
'writer(s)'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 637
'mile high stadium'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  14%|█▎        | 576/4257 [02:44<25:19,  2.42 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  14%|█▎        | 578/4257 [02:44<18:00,  3.40 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  14%|█▎        | 580/4257 [02:44<14:23,  4.26 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1249
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 483
'>' not supported between instances of 'str' and 'int''brazil scorers'

'str' object is not callable

Map (num_proc=16):  14%|█▎        | 581/4257 [02:45<17:22,  3.53 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  14%|█▎        | 582/4257 [02:45<16:44,  3.66 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  14%|█▎        | 583/4257 [02:45<14:08,  4.33 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1096
'no'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  14%|█▎        | 584/4257 [02:45<17:30,  3.50 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  14%|█▎        | 585/4257 [02:46<15:49,  3.87 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 244
Could not convert string '12.14 (86)18.14 (122)' to numeric
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 905
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  14%|█▍        | 586/4257 [02:46<20:05,  3.05 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  14%|█▍        | 588/4257 [02:46<13:45,  4.45 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRREEEERRRRRRR  1410164

invalid syntax (<string>, line 1)single positional indexer is out-of-bounds

'brazil scorers''brazil scorers'

'str' object is not callable'str' object is not callable

Map (num_proc=16):  14%|█▍        | 589/4257 [02:47<14:26,  4.24 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

'brazil scorers'
'str' object is not callable

Map (num_proc=16):  14%|█▍        | 592/4257 [02:47<11:01,  5.54 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  14%|█▍        | 593/4257 [02:47<12:55,  4.73 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1249
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  14%|█▍        | 594/4257 [02:48<16:51,  3.62 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  14%|█▍        | 596/4257 [02:48<15:56,  3.83 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 556
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1562
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Map (num_proc=16):  14%|█▍        | 598/4257 [02:49<16:42,  3.65 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRREEEERRRRRRR  795
318invalid syntax. Perhaps you forgot a comma? (<string>, line 1)

The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 717
could not convert string to float: '05.03.80'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  14%|█▍        | 599/4257 [02:50<27:13,  2.24 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 81
'raymond felton'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  14%|█▍        | 600/4257 [02:50<25:26,  2.40 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  14%|█▍        | 601/4257 [02:50<21:31,  2.83 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  14%|█▍        | 603/4257 [02:51<15:20,  3.97 examples/s]

EEEERRRRRRR 637
single positional indexer is out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  14%|█▍        | 604/4257 [02:51<17:33,  3.47 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  14%|█▍        | 606/4257 [02:51<13:46,  4.42 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  14%|█▍        | 607/4257 [02:52<13:20,  4.56 examples/s]

EEEERRRRRRR 1249
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  14%|█▍        | 608/4257 [02:52<13:52,  4.38 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRREEEERRRRRRR  14905

left side of interval must be <= right side'>' not supported between instances of 'str' and 'int'

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  14%|█▍        | 611/4257 [02:52<13:14,  4.59 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  14%|█▍        | 613/4257 [02:53<11:46,  5.16 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1100
'attorney general'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  14%|█▍        | 616/4257 [02:53<11:23,  5.33 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

'brazil scorers'

Map (num_proc=16):  15%|█▍        | 618/4257 [02:53<09:58,  6.08 examples/s]

'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'EEEERRRRRRR
 'str' object is not callable81

Map (num_proc=16):  15%|█▍        | 621/4257 [02:54<10:05,  6.01 examples/s]

Could not convert string 'raymond felton (23)stephen jackson (30)stephen jackson (26)stephen jackson (22)stephen jackson (33)gerald wallace (21)stephen jackson (29)stephen jackson (35)gerald wallace (32)gerald wallace (27)' to numeric
EEEERRRRRRR 404
'location'
EEEERRRRRRR 796
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  15%|█▍        | 622/4257 [02:54<11:57,  5.07 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  15%|█▍        | 623/4257 [02:55<12:03,  5.03 examples/s]

EEEERRRRRRR 1563
'total score'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 556
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  15%|█▍        | 625/4257 [02:55<13:21,  4.53 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 165
Can only compare identically-labeled Series objects
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  15%|█▍        | 626/4257 [02:55<15:26,  3.92 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 244
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  15%|█▍        | 627/4257 [02:56<18:01,  3.36 examples/s]

EEEERRRRRRR 485
'winner'
EEEERRRRRRR 1410
'date | time | score | set 1 | set 2 | set 3 | total'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  15%|█▍        | 628/4257 [02:56<18:19,  3.30 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'

Map (num_proc=16):  15%|█▍        | 629/4257 [02:56<17:28,  3.46 examples/s]

'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  15%|█▍        | 631/4257 [02:57<17:39,  3.42 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  15%|█▍        | 633/4257 [02:57<12:24,  4.87 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  15%|█▍        | 634/4257 [02:57<11:17,  5.35 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  15%|█▍        | 635/4257 [02:58<13:25,  4.50 examples/s]

EEEERRRRRRR 906
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  15%|█▍        | 636/4257 [02:58<13:36,  4.43 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 717
could not convert string to float: '50.56.8'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  15%|█▍        | 637/4257 [02:58<19:17,  3.13 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  15%|█▌        | 639/4257 [02:59<15:06,  3.99 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 404
'location'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  15%|█▌        | 640/4257 [02:59<13:12,  4.56 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 796
'>=' not supported between instances of 'str' and 'int'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  15%|█▌        | 642/4257 [02:59<12:07,  4.97 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  15%|█▌        | 644/4257 [03:00<12:32,  4.80 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  15%|█▌        | 646/4257 [03:00<12:13,  4.92 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  15%|█▌        | 648/4257 [03:00<11:37,  5.17 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 485
'winner'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  15%|█▌        | 649/4257 [03:01<13:13,  4.55 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 322
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  15%|█▌        | 650/4257 [03:01<12:05,  4.97 examples/s]

EEEERRRRRRR 1103
'location'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 81
'raymond felton'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1564
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRR 14
'(' was never closed (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 166
unsupported operand type(s) for -: 'str' and 'str'
EEEERRRRRRR 244
Cannot perform 'ror_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  15%|█▌        | 651/4257 [03:02<21:26,  2.80 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

<string>:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.

EEEERRRRRRR 638
Can only use .str accessor with string values!

Map (num_proc=16):  15%|█▌        | 652/4257 [03:02<24:49,  2.42 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 404
invalid literal for int() with base 10: 'l 100'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
EEEERRRRRRR'str' object is not callable
556

Map (num_proc=16):  15%|█▌        | 654/4257 [03:03<22:54,  2.62 examples/s]

Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1410
invalid syntax (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  15%|█▌        | 655/4257 [03:03<24:03,  2.49 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  15%|█▌        | 656/4257 [03:04<21:54,  2.74 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  15%|█▌        | 657/4257 [03:04<19:31,  3.07 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1104
invalid literal for int() with base 10: 'l 99 '
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1251
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  15%|█▌        | 659/4257 [03:05<22:01,  2.72 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  16%|█▌        | 660/4257 [03:05<21:11,  2.83 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  16%|█▌        | 661/4257 [03:05<21:18,  2.81 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 796
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  16%|█▌        | 662/4257 [03:06<22:40,  2.64 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  16%|█▌        | 664/4257 [03:06<15:20,  3.90 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR'brazil scorers'
717'str' object is not callable

'time'

Map (num_proc=16):  16%|█▌        | 667/4257 [03:07<13:46,  4.35 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  16%|█▌        | 668/4257 [03:07<15:03,  3.97 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  16%|█▌        | 669/4257 [03:07<15:05,  3.96 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 486
unsupported operand type(s) for -: 'str' and 'str'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1567
The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRR 911
'winner / nominee(s)'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  16%|█▌        | 671/4257 [03:08<19:25,  3.08 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  16%|█▌        | 673/4257 [03:08<15:20,  3.89 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  16%|█▌        | 675/4257 [03:09<12:58,  4.60 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  16%|█▌        | 676/4257 [03:09<14:03,  4.24 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  16%|█▌        | 677/4257 [03:09<14:56,  3.99 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'

Map (num_proc=16):  16%|█▌        | 678/4257 [03:10<13:37,  4.38 examples/s]

'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  16%|█▌        | 681/4257 [03:10<10:01,  5.95 examples/s]

EEEERRRRRRR 244
invalid syntax (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 638
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 82
'games'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 796
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 556
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 322
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'

Map (num_proc=16):  16%|█▌        | 682/4257 [03:11<20:18,  2.93 examples/s]

'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1252
'swim'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  16%|█▌        | 685/4257 [03:11<15:46,  3.77 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  16%|█▌        | 686/4257 [03:12<16:14,  3.66 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  16%|█▌        | 687/4257 [03:12<16:59,  3.50 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1570
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  16%|█▌        | 688/4257 [03:13<23:50,  2.49 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 405
unsupported operand type(s) for -: 'str' and 'str'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  16%|█▌        | 689/4257 [03:13<26:14,  2.27 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  16%|█▌        | 690/4257 [03:14<23:22,  2.54 examples/s]

EEEERRRRRRR 166
could not convert string to float: '1:46.75'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  16%|█▌        | 691/4257 [03:14<21:24,  2.78 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 718
'date'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  16%|█▋        | 692/4257 [03:14<23:19,  2.55 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'

Map (num_proc=16):  16%|█▋        | 693/4257 [03:15<21:10,  2.81 examples/s]

'str' object is not callable
'brazil scorers'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5'str' object is not callable

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  16%|█▋        | 696/4257 [03:15<10:47,  5.50 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
EEEERRRRRRR 1410
'>=' not supported between instances of 'str' and 'int'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  16%|█▋        | 698/4257 [03:15<10:35,  5.60 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  16%|█▋        | 699/4257 [03:15<10:30,  5.64 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 557
unsupported operand type(s) for -: 'str' and 'str'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  16%|█▋        | 701/4257 [03:16<14:50,  4.00 examples/s]

EEEERRRRRRR 83
'deleted row'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  17%|█▋        | 703/4257 [03:17<14:11,  4.17 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  17%|█▋        | 705/4257 [03:17<12:42,  4.66 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 17
invalid literal for int() with base 10: '6 - 4 '
'brazil scorers'

Map (num_proc=16):  17%|█▋        | 707/4257 [03:17<10:39,  5.55 examples/s]

'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  17%|█▋        | 710/4257 [03:17<08:05,  7.31 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 245
'us open'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  17%|█▋        | 711/4257 [03:18<11:49,  5.00 examples/s]

EEEERRRRRRR 1570
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  17%|█▋        | 712/4257 [03:18<15:14,  3.88 examples/s]

EEEERRRRRRR 1109
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1253
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRR 322
Out of bounds nanosecond timestamp: march 31, at position 0
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  17%|█▋        | 713/4257 [03:19<18:05,  3.27 examples/s]

EEEERRRRRRR 640
'This is our God'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  17%|█▋        | 714/4257 [03:19<20:26,  2.89 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  17%|█▋        | 715/4257 [03:20<19:52,  2.97 examples/s]

EEEERRRRRRR 487
invalid literal for int() with base 10: 'w'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 405
single positional indexer is out-of-bounds
EEEERRRRRRR 913
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
'brazil scorers'
'str' object is not callableGenerating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  17%|█▋        | 716/4257 [03:20<19:30,  3.03 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 718
'Name'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  17%|█▋        | 717/4257 [03:20<21:42,  2.72 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'EEEERRRRRRR
'brazil scorers' 'str' object is not callable
797

Map (num_proc=16):  17%|█▋        | 718/4257 [03:21<22:00,  2.68 examples/s]

'str' object is not callable

The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

'brazil scorers'
'str' object is not callable

Map (num_proc=16):  17%|█▋        | 720/4257 [03:21<15:41,  3.76 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 83
'deleted row'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  17%|█▋        | 721/4257 [03:22<22:44,  2.59 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 17
'hard'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  17%|█▋        | 723/4257 [03:22<19:38,  3.00 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR

Map (num_proc=16):  17%|█▋        | 724/4257 [03:23<18:39,  3.16 examples/s]

245
'win-loss'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  17%|█▋        | 726/4257 [03:23<15:55,  3.69 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  17%|█▋        | 727/4257 [03:23<15:45,  3.73 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  17%|█▋        | 728/4257 [03:24<15:59,  3.68 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5EEEERRRRRRR
 1110
'col'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 167
positional indexers are out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR

Map (num_proc=16):  17%|█▋        | 729/4257 [03:24<22:07,  2.66 examples/s]

 718
'european record'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1254
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  17%|█▋        | 731/4257 [03:25<18:01,  3.26 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  17%|█▋        | 732/4257 [03:25<18:04,  3.25 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 643
single positional indexer is out-of-bounds
EEEERRRRRRR 557
invalid literal for int() with base 10: '71 + 71 + 65 = 207'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  17%|█▋        | 733/4257 [03:25<20:18,  2.89 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1571
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 405
'str' object has no attribute 'astype'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  17%|█▋        | 734/4257 [03:26<28:42,  2.05 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  17%|█▋        | 735/4257 [03:26<24:16,  2.42 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  17%|█▋        | 737/4257 [03:27<16:50,  3.48 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 322
'numpy.bool' object has no attribute 'reset_index'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  17%|█▋        | 739/4257 [03:27<14:59,  3.91 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 797
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1110
'>' not supported between instances of 'str' and 'int'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  17%|█▋        | 741/4257 [03:28<17:57,  3.26 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 914
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  17%|█▋        | 743/4257 [03:29<18:02,  3.25 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 718
'brazil scorers''record set'

'str' object is not callable

Map (num_proc=16):  18%|█▊        | 745/4257 [03:29<13:33,  4.32 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  18%|█▊        | 746/4257 [03:29<13:49,  4.23 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 83
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  18%|█▊        | 748/4257 [03:30<15:05,  3.88 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  18%|█▊        | 749/4257 [03:30<13:46,  4.25 examples/s]

EEEERRRRRRR 1254
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  18%|█▊        | 750/4257 [03:30<16:59,  3.44 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1413
'>=' not supported between instances of 'str' and 'int'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  18%|█▊        | 751/4257 [03:31<17:43,  3.30 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

<string>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
Map (num_proc=16):  18%|█▊        | 753/4257 [03:31<13:43,  4.25 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  18%|█▊        | 754/4257 [03:31<12:54,  4.52 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 17
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  18%|█▊        | 755/4257 [03:32<17:19,  3.37 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 168
single positional indexer is out-of-bounds
EEEERRRRRRR 1573
invalid literal for int() with base 10: 'fred jones (23)'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  18%|█▊        | 756/4257 [03:32<17:02,  3.42 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  18%|█▊        | 758/4257 [03:32<14:45,  3.95 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  18%|█▊        | 759/4257 [03:32<13:57,  4.18 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  18%|█▊        | 760/4257 [03:33<13:14,  4.40 examples/s]

EEEERRRRRRR 557
'<' not supported between instances of 'str' and 'int'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  18%|█▊        | 761/4257 [03:33<12:15,  4.76 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR EEEERRRRRRR487
798'location'

single positional indexer is out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  18%|█▊        | 762/4257 [03:33<11:55,  4.89 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 245
'win-loss'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  18%|█▊        | 763/4257 [03:33<16:47,  3.47 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  18%|█▊        | 765/4257 [03:34<15:10,  3.84 examples/s]

EEEERRRRRRR 1112
'cardinality'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  18%|█▊        | 766/4257 [03:34<15:06,  3.85 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1413
single positional indexer is out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  18%|█▊        | 768/4257 [03:35<15:59,  3.64 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 83
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 915
'Total'
EEEERRRRRRR 718
'Date'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 324
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Map (num_proc=16):  18%|█▊        | 769/4257 [03:36<23:20,  2.49 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'

Map (num_proc=16):  18%|█▊        | 770/4257 [03:36<26:11,  2.22 examples/s]

'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1254
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
'brazil scorers'
'str' object is not callableGenerating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  18%|█▊        | 773/4257 [03:37<17:02,  3.41 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  18%|█▊        | 774/4257 [03:37<15:55,  3.65 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers''brazil scorers'

'str' object is not callable'str' object is not callable

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  18%|█▊        | 777/4257 [03:37<13:48,  4.20 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 18
'str' object has no attribute 'sum'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  18%|█▊        | 780/4257 [03:38<14:11,  4.08 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  18%|█▊        | 782/4257 [03:39<13:52,  4.17 examples/s]

EEEERRRRRRR 557
Cannot convert non-finite values (NA or inf) to integer
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  18%|█▊        | 784/4257 [03:39<12:40,  4.57 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  18%|█▊        | 786/4257 [03:39<10:17,  5.63 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 799
invalid literal for int() with base 10: 'postponed'
EEEERRRRRRR 407
'name'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1413
'>=' not supported between instances of 'str' and 'int'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 169
'50cc'
EEEERRRRRRR 718
'Date'
EEEERRRRRRR 1116
invalid syntax (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
EEEERRRRRRR'str' object is not callable
1576

Map (num_proc=16):  19%|█▊        | 788/4257 [03:41<20:51,  2.77 examples/s]

'col'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 644
0
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 324
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  19%|█▊        | 789/4257 [03:41<24:23,  2.37 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  19%|█▊        | 790/4257 [03:42<25:15,  2.29 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 915
'brazil 100%'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  19%|█▊        | 792/4257 [03:42<20:16,  2.85 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 557
single positional indexer is out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  19%|█▊        | 793/4257 [03:43<22:21,  2.58 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  19%|█▊        | 794/4257 [03:43<21:19,  2.71 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  19%|█▊        | 795/4257 [03:43<20:45,  2.78 examples/s]

EEEERRRRRRR 487
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  19%|█▊        | 796/4257 [03:44<18:59,  3.04 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 83
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  19%|█▊        | 798/4257 [03:45<20:43,  2.78 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5'brazil scorers'

'str' object is not callable

Map (num_proc=16):  19%|█▉        | 800/4257 [03:45<14:21,  4.01 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 407
'number'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  19%|█▉        | 801/4257 [03:45<14:43,  3.91 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  19%|█▉        | 802/4257 [03:45<18:06,  3.18 examples/s]

'brazil scorers'
'str' object is not callable
EEEERRRRRRR 557
'<=' not supported between instances of 'str' and 'int'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  19%|█▉        | 804/4257 [03:46<14:07,  4.08 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1254
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  19%|█▉        | 805/4257 [03:46<15:14,  3.78 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  19%|█▉        | 806/4257 [03:46<17:11,  3.34 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  19%|█▉        | 807/4257 [03:47<17:05,  3.36 examples/s]

EEEERRRRRRR 1415
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRR 246
'in <string>' requires string as left operand, not int
'brazil scorers'Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  19%|█▉        | 809/4257 [03:47<15:29,  3.71 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  19%|█▉        | 810/4257 [03:47<15:17,  3.76 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 324'brazil scorers'

'str' object is not callableThe truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Map (num_proc=16):  19%|█▉        | 812/4257 [03:48<11:20,  5.06 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 799
'june 9'
EEEERRRRRRR 170
'detectable by'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  19%|█▉        | 813/4257 [03:48<14:18,  4.01 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 718
'location'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  19%|█▉        | 814/4257 [03:49<19:58,  2.87 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  19%|█▉        | 815/4257 [03:49<16:32,  3.47 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 646
Cannot perform 'rand_' with a dtyped [int64] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  19%|█▉        | 816/4257 [03:49<15:44,  3.64 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 916
"None of [Index([2006, 2007], dtype='int64')] are in the [index]"
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  19%|█▉        | 817/4257 [03:50<20:34,  2.79 examples/s]

EEEERRRRRRR 1576
'col 1'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  19%|█▉        | 818/4257 [03:50<22:02,  2.60 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  19%|█▉        | 820/4257 [03:50<15:16,  3.75 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  19%|█▉        | 822/4257 [03:51<10:54,  5.25 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 84
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 557
invalid literal for int() with base 10: '71 + 71 + 65 = 207'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  19%|█▉        | 823/4257 [03:52<20:41,  2.77 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  19%|█▉        | 825/4257 [03:52<15:38,  3.66 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  19%|█▉        | 828/4257 [03:52<11:04,  5.16 examples/s]

EEEERRRRRRR 487
'location'
'brazil scorers'
'str' object is not callable
EEEERRRRRRR 408
positional indexers are out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  19%|█▉        | 830/4257 [03:53<12:44,  4.48 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  20%|█▉        | 831/4257 [03:53<11:58,  4.77 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1415
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  20%|█▉        | 832/4257 [03:53<14:17,  4.00 examples/s]

EEEERRRRRRR 324
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  20%|█▉        | 833/4257 [03:54<15:17,  3.73 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1255
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
EEEERRRRRRR 1117
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Map (num_proc=16):  20%|█▉        | 834/4257 [03:54<15:19,  3.72 examples/s]

'brazil scorers'
EEEERRRRRRR 'str' object is not callable20

Can only compare identically-labeled Series objects
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  20%|█▉        | 836/4257 [03:54<12:58,  4.39 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  20%|█▉        | 837/4257 [03:54<12:48,  4.45 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  20%|█▉        | 838/4257 [03:55<12:20,  4.62 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  20%|█▉        | 840/4257 [03:55<16:28,  3.46 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'EEEERRRRRRR
 'str' object is not callable1577
EEEERRRRRRR

Map (num_proc=16):  20%|█▉        | 841/4257 [03:56<17:48,  3.20 examples/s]

 The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().170

'detectable by'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 487
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 719
'first_name'
EEEERRRRRRR 247
'>=' not supported between instances of 'str' and 'float'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 799
'<=' not supported between instances of 'str' and 'int'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  20%|█▉        | 843/4257 [03:57<21:22,  2.66 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1417
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  20%|█▉        | 845/4257 [03:57<20:52,  2.72 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  20%|█▉        | 846/4257 [03:58<20:29,  2.77 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  20%|█▉        | 847/4257 [03:58<17:38,  3.22 examples/s]

EEEERRRRRRR 84
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  20%|█▉        | 848/4257 [03:58<18:53,  3.01 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  20%|█▉        | 850/4257 [03:58<13:46,  4.12 examples/s]

EEEERRRRRRR 919
index 12 is out of bounds for axis 0 with size 12
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 408
Cannot perform 'ror_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  20%|█▉        | 851/4257 [03:59<18:40,  3.04 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 647
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 558
"None of [Index([ -4046,  25168,  -5356,  -8483,   -217,   -482,  -2510,  -1224,   -911,\n        -3315,   -311,  -2379,   -745,   -348, -11543],\n      dtype='int64')] are in the [columns]"
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  20%|██        | 853/4257 [04:00<16:23,  3.46 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  20%|██        | 854/4257 [04:00<15:35,  3.64 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  20%|██        | 856/4257 [04:00<13:42,  4.14 examples/s]

EEEERRRRRRR 20
single positional indexer is out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  20%|██        | 858/4257 [04:00<10:34,  5.36 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1577
'august 24'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  20%|██        | 859/4257 [04:01<15:20,  3.69 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  20%|██        | 860/4257 [04:01<16:05,  3.52 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  20%|██        | 861/4257 [04:02<16:12,  3.49 examples/s]

'brazil scorers'
'str' object is not callable
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  20%|██        | 864/4257 [04:02<12:14,  4.62 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 171
'time'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  20%|██        | 865/4257 [04:02<15:03,  3.75 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  20%|██        | 867/4257 [04:03<12:20,  4.58 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 719
'title'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  20%|██        | 868/4257 [04:03<12:06,  4.67 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  20%|██        | 869/4257 [04:03<13:20,  4.23 examples/s]

EEEERRRRRRR 1118
The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  20%|██        | 871/4257 [04:03<10:37,  5.31 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  20%|██        | 872/4257 [04:04<09:59,  5.65 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 'brazil scorers'1259

'str' object is not callableinvalid literal for int() with base 10: '15 , 18 '

Map (num_proc=16):  21%|██        | 874/4257 [04:04<08:50,  6.38 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.51417

The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  21%|██        | 876/4257 [04:04<09:21,  6.02 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  21%|██        | 878/4257 [04:05<11:44,  4.79 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  21%|██        | 879/4257 [04:05<10:52,  5.18 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  21%|██        | 881/4257 [04:05<09:59,  5.63 examples/s]

EEEERRRRRRR 84
'str' object has no attribute 'month'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 801
Can only compare identically-labeled Series objects
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRREEEERRRRRRR  408488

The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  21%|██        | 882/4257 [04:06<15:23,  3.65 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 921
'no'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  21%|██        | 883/4257 [04:06<16:29,  3.41 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  21%|██        | 884/4257 [04:06<15:10,  3.70 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  21%|██        | 886/4257 [04:07<12:50,  4.37 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 21
unsupported operand type(s) for -: 'str' and 'str'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  21%|██        | 888/4257 [04:07<14:08,  3.97 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

<string>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

EEEERRRRRRR 558
unsupported operand type(s) for -: 'str' and 'str'

Map (num_proc=16):  21%|██        | 889/4257 [04:08<14:36,  3.84 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  21%|██        | 891/4257 [04:08<12:29,  4.49 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  21%|██        | 892/4257 [04:08<12:56,  4.34 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 648
'team'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  21%|██        | 894/4257 [04:09<13:14,  4.23 examples/s]

'brazil scorers'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  21%|██        | 896/4257 [04:09<12:45,  4.39 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 171
'time'
EEEERRRRRRR 1583
invalid literal for int() with base 10: 'l 28 '
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  21%|██        | 897/4257 [04:09<12:36,  4.44 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR

Map (num_proc=16):  21%|██        | 899/4257 [04:10<12:54,  4.34 examples/s]

 720
Lengths must match to compare
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1261
'name'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  21%|██        | 901/4257 [04:10<12:35,  4.44 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 921
'no'

Map (num_proc=16):  21%|██        | 902/4257 [04:11<13:02,  4.29 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  21%|██        | 904/4257 [04:11<12:38,  4.42 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 85
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  21%|██▏       | 905/4257 [04:11<15:27,  3.62 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable'brazil scorers'

'str' object is not callable

Map (num_proc=16):  21%|██▏       | 906/4257 [04:12<15:58,  3.49 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  21%|██▏       | 908/4257 [04:12<12:34,  4.44 examples/s]

EEEERRRRRRR 1120
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRR 1419
single positional indexer is out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  21%|██▏       | 909/4257 [04:12<13:29,  4.14 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR'brazil scorers'
488
'str' object is not callableCan only use .dt accessor with datetimelike values

Map (num_proc=16):  21%|██▏       | 910/4257 [04:13<13:51,  4.03 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  21%|██▏       | 911/4257 [04:13<13:36,  4.10 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  21%|██▏       | 912/4257 [04:13<13:44,  4.06 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

<string>:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
Map (num_proc=16):  21%|██▏       | 914/4257 [04:13<12:12,  4.56 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 721
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  21%|██▏       | 915/4257 [04:14<18:26,  3.02 examples/s]

EEEERRRRRRR 409'brazil scorers'
'str' object has no attribute 'astype'

'str' object is not callable
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 21
can only concatenate str (not "int") to str

Map (num_proc=16):  22%|██▏       | 918/4257 [04:15<15:41,  3.54 examples/s]

EEEERRRRRRR 248
index 0 is out of bounds for axis 0 with size 0
EEEERRRRRRR 328
invalid literal for int() with base 10: 'l'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 559
'years row'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1585
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  22%|██▏       | 920/4257 [04:16<18:42,  2.97 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  22%|██▏       | 922/4257 [04:16<18:14,  3.05 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  22%|██▏       | 923/4257 [04:17<17:31,  3.17 examples/s]

EEEERRRRRRR 801
'score_team_2'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  22%|██▏       | 924/4257 [04:17<16:05,  3.45 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  22%|██▏       | 925/4257 [04:17<14:48,  3.75 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

<string>:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.

EEEERRRRRRR 648
The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  22%|██▏       | 926/4257 [04:18<18:26,  3.01 examples/s]

EEEERRRRRRR 86
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1262
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  22%|██▏       | 927/4257 [04:18<21:25,  2.59 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  22%|██▏       | 928/4257 [04:18<18:03,  3.07 examples/s]

EEEERRRRRRR 721
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1120
'a external (cm 2)'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  22%|██▏       | 929/4257 [04:19<26:12,  2.12 examples/s]

EEEERRRRRRR 1421
'no opinion'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  22%|██▏       | 930/4257 [04:20<28:08,  1.97 examples/s]

'brazil scorers''brazil scorers'

'str' object is not callable'str' object is not callable

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  22%|██▏       | 933/4257 [04:20<14:58,  3.70 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  22%|██▏       | 934/4257 [04:20<18:24,  3.01 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  22%|██▏       | 936/4257 [04:21<14:38,  3.78 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  22%|██▏       | 937/4257 [04:21<13:11,  4.19 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  22%|██▏       | 939/4257 [04:21<10:21,  5.34 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 411
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  22%|██▏       | 940/4257 [04:21<11:14,  4.92 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  22%|██▏       | 941/4257 [04:22<10:03,  5.49 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  22%|██▏       | 942/4257 [04:22<12:07,  4.56 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 649
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Map (num_proc=16):  22%|██▏       | 944/4257 [04:22<09:52,  5.59 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 'brazil scorers'86

'str' object is not callable'result row 2003'

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  22%|██▏       | 946/4257 [04:22<09:04,  6.08 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  22%|██▏       | 948/4257 [04:23<07:43,  7.14 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  22%|██▏       | 949/4257 [04:23<07:18,  7.55 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  22%|██▏       | 950/4257 [04:23<07:06,  7.75 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 488
'float' object has no attribute 'item'
EEEERRRRRRR 1265
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  22%|██▏       | 951/4257 [04:23<12:54,  4.27 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  22%|██▏       | 953/4257 [04:24<10:41,  5.15 examples/s]

EEEERRRRRRR 22
single positional indexer is out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  22%|██▏       | 954/4257 [04:24<09:46,  5.63 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 724
invalid literal for int() with base 10: 'wells (15'

Map (num_proc=16):  22%|██▏       | 955/4257 [04:24<11:07,  4.95 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  22%|██▏       | 956/4257 [04:24<10:20,  5.32 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 559
'>=' not supported between instances of 'str' and 'int'
EEEERRRRRRR 1421
Could not convert string '28%29%42%20%16%11%' to numeric
EEEERRRRRRR 249Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

invalid literal for int() with base 10: '7 - 5 '
EEEERRRRRRR 174
Can only compare identically-labeled Series objects
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1120
index 0 is out of bounds for axis 0 with size 0
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  22%|██▏       | 957/4257 [04:25<21:10,  2.60 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  23%|██▎       | 958/4257 [04:25<20:04,  2.74 examples/s]

EEEERRRRRRR 86
invalid decimal literal (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1586
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 411
'winner'

Map (num_proc=16):  23%|██▎       | 959/4257 [04:26<25:29,  2.16 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  23%|██▎       | 961/4257 [04:26<17:47,  3.09 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  23%|██▎       | 962/4257 [04:27<22:09,  2.48 examples/s]

EEEERRRRRRR 926
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  23%|██▎       | 963/4257 [04:28<27:18,  2.01 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  23%|██▎       | 965/4257 [04:28<17:06,  3.21 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  23%|██▎       | 966/4257 [04:28<15:46,  3.48 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  23%|██▎       | 967/4257 [04:28<14:45,  3.72 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 803
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 488'brazil scorers'

Can only use .dt accessor with datetimelike values
'str' object is not callable

Map (num_proc=16):  23%|██▎       | 968/4257 [04:29<14:48,  3.70 examples/s]

EEEERRRRRRR 328
invalid syntax (<string>, line 0)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  23%|██▎       | 969/4257 [04:29<14:37,  3.75 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 724
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  23%|██▎       | 971/4257 [04:29<13:24,  4.08 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 22
'int' object has no attribute 'shift'

Map (num_proc=16):  23%|██▎       | 972/4257 [04:30<16:17,  3.36 examples/s]

EEEERRRRRRR 559
Cannot use method 'nlargest' with dtype object
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  23%|██▎       | 973/4257 [04:30<14:15,  3.84 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  23%|██▎       | 974/4257 [04:30<13:36,  4.02 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  23%|██▎       | 976/4257 [04:30<11:35,  4.72 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  23%|██▎       | 978/4257 [04:31<09:32,  5.73 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  23%|██▎       | 979/4257 [04:31<09:59,  5.47 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1586
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  23%|██▎       | 980/4257 [04:31<10:55,  5.00 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 174
can only concatenate str (not "int") to str
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 926
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  23%|██▎       | 981/4257 [04:32<18:21,  2.97 examples/s]

EEEERRRRRRR 249
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  23%|██▎       | 983/4257 [04:32<12:14,  4.46 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 87
'score to par'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  23%|██▎       | 984/4257 [04:33<17:17,  3.15 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 411
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  23%|██▎       | 986/4257 [04:33<14:05,  3.87 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1121

Map (num_proc=16):  23%|██▎       | 988/4257 [04:33<11:20,  4.81 examples/s]

The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  23%|██▎       | 989/4257 [04:34<12:35,  4.32 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 649
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  23%|██▎       | 991/4257 [04:34<13:37,  4.00 examples/s]

EEEERRRRRRR 488
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1586
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  23%|██▎       | 992/4257 [04:35<18:02,  3.02 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  23%|██▎       | 993/4257 [04:35<17:28,  3.11 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  23%|██▎       | 996/4257 [04:35<10:54,  4.98 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR

Map (num_proc=16):  23%|██▎       | 997/4257 [04:36<11:23,  4.77 examples/s]

1422
invalid literal for int() with base 10: '2.2 '
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  23%|██▎       | 998/4257 [04:36<12:00,  4.52 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  23%|██▎       | 1000/4257 [04:36<09:43,  5.59 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 174
Could not convert string '02' to numeric
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  24%|██▎       | 1002/4257 [04:36<10:18,  5.26 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 927
single positional indexer is out-of-bounds
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  24%|██▎       | 1003/4257 [04:37<11:35,  4.68 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

<string>:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
Map (num_proc=16):  24%|██▎       | 1004/4257 [04:37<13:08,  4.13 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 411
'str' object has no attribute 'astype'
EEEERRRRRRR'brazil scorers'
22'str' object is not callable
Can only use .dt accessor with datetimelike values

Map (num_proc=16):  24%|██▎       | 1006/4257 [04:38<12:05,  4.48 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  24%|██▎       | 1007/4257 [04:38<12:58,  4.18 examples/s]

EEEERRRRRRR 560
'engine'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1121
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Map (num_proc=16):  24%|██▎       | 1010/4257 [04:38<12:22,  4.38 examples/s]

EEEERRRRRRR Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.51271

invalid literal for int() with base 10: 'w 116 '
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 88
could not convert string to float: '14.20 (104)'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  24%|██▎       | 1011/4257 [04:39<17:51,  3.03 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 804
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRR 328
invalid literal for int() with base 10: 'l 83 'EEEERRRRRRR
 249
Can only use .str accessor with string values!
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  24%|██▍       | 1012/4257 [04:40<20:36,  2.62 examples/s]

'brazil scorers'
'str' object is not callable
EEEERRRRRRR 488
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  24%|██▍       | 1014/4257 [04:40<17:17,  3.13 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  24%|██▍       | 1015/4257 [04:40<16:00,  3.38 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 174
'>' not supported between instances of 'str' and 'int'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  24%|██▍       | 1016/4257 [04:41<16:47,  3.22 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 726
'>=' not supported between instances of 'str' and 'int'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  24%|██▍       | 1017/4257 [04:42<27:54,  1.94 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  24%|██▍       | 1020/4257 [04:42<16:59,  3.17 examples/s]

EEEERRRRRRR 1423
StringMethods.split() takes from 1 to 2 positional arguments but 3 were given
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  24%|██▍       | 1021/4257 [04:42<14:48,  3.64 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 805
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 927
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  24%|██▍       | 1022/4257 [04:43<14:51,  3.63 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 650
'declination ( j2000)'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1122
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  24%|██▍       | 1023/4257 [04:44<26:15,  2.05 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  24%|██▍       | 1024/4257 [04:44<22:19,  2.41 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 411
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  24%|██▍       | 1025/4257 [04:45<22:51,  2.36 examples/s]

EEEERRRRRRR 560
'engine'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1271
invalid literal for int() with base 10: 'w 116'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  24%|██▍       | 1026/4257 [04:45<28:55,  1.86 examples/s]

EEEERRRRRRR 23
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
'brazil scorers'Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1591
single positional indexer is out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  24%|██▍       | 1028/4257 [04:46<21:00,  2.56 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  24%|██▍       | 1029/4257 [04:46<20:04,  2.68 examples/s]

'brazil scorers'Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  24%|██▍       | 1031/4257 [04:46<14:56,  3.60 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  24%|██▍       | 1032/4257 [04:47<14:58,  3.59 examples/s]

'brazil scorers'
'str' object is not callable
EEEERRRRRRR 488
0Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  24%|██▍       | 1034/4257 [04:47<11:09,  4.81 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 805
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  24%|██▍       | 1035/4257 [04:47<12:18,  4.36 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  24%|██▍       | 1036/4257 [04:47<13:34,  3.95 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 174
Cannot use method 'nlargest' with dtype object
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 329
unsupported operand type(s) for -: 'str' and 'str'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  24%|██▍       | 1037/4257 [04:48<23:03,  2.33 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  24%|██▍       | 1038/4257 [04:49<20:14,  2.65 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1124
'team'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  24%|██▍       | 1041/4257 [04:49<15:44,  3.41 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  25%|██▍       | 1043/4257 [04:49<12:04,  4.44 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  25%|██▍       | 1044/4257 [04:50<16:43,  3.20 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 561
Can only use .dt accessor with datetimelike values

Map (num_proc=16):  25%|██▍       | 1045/4257 [04:50<16:42,  3.20 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  25%|██▍       | 1048/4257 [04:51<11:38,  4.60 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR'brazil scorers'
726'str' object is not callable

'>=' not supported between instances of 'str' and 'int'

Map (num_proc=16):  25%|██▍       | 1050/4257 [04:51<09:59,  5.35 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 929
EEEERRRRRRRThe truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
250
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  25%|██▍       | 1052/4257 [04:52<11:30,  4.64 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 805
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRR 489
'>=' not supported between instances of 'str' and 'float'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  25%|██▍       | 1053/4257 [04:52<12:53,  4.14 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  25%|██▍       | 1054/4257 [04:52<13:27,  3.97 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 412
'nominations'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  25%|██▍       | 1055/4257 [04:53<19:52,  2.69 examples/s]

EEEERRRRRRR 1424
invalid syntax (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  25%|██▍       | 1056/4257 [04:53<17:18,  3.08 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 650
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callableEEEERRRRRRR

Map (num_proc=16):  25%|██▍       | 1057/4257 [04:54<21:47,  2.45 examples/s]

90
False
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  25%|██▍       | 1059/4257 [04:55<19:41,  2.71 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  25%|██▍       | 1061/4257 [04:55<13:18,  4.00 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  25%|██▍       | 1062/4257 [04:55<13:27,  3.96 examples/s]

'brazil scorers''brazil scorers'

'str' object is not callable'str' object is not callable

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  25%|██▌       | 1066/4257 [04:55<06:50,  7.77 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  25%|██▌       | 1068/4257 [04:56<11:11,  4.75 examples/s]

EEEERRRRRRR 930
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  25%|██▌       | 1071/4257 [04:56<08:45,  6.07 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 805
Cannot perform 'rand_' with a dtyped [bool] array and scalar of type [bool]
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1424
invalid syntax (<string>, line 1)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 175
EEEERRRRRRR 'str' object has no attribute 'year'329

unsupported operand type(s) for -: 'str' and 'str'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  25%|██▌       | 1073/4257 [04:57<12:30,  4.24 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 25
Can only use .dt accessor with datetimelike values
EEEERRRRRRR 1273
'col'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  25%|██▌       | 1074/4257 [04:58<15:00,  3.54 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  25%|██▌       | 1075/4257 [04:58<14:16,  3.71 examples/s]

EEEERRRRRRR 561
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  25%|██▌       | 1076/4257 [04:58<12:47,  4.14 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 726
'>=' not supported between instances of 'str' and 'int'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  25%|██▌       | 1077/4257 [04:58<16:38,  3.18 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  25%|██▌       | 1078/4257 [04:59<16:43,  3.17 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  25%|██▌       | 1080/4257 [04:59<13:19,  3.97 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 251
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  25%|██▌       | 1081/4257 [04:59<15:07,  3.50 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 90
index 0 is out of bounds for axis 0 with size 0
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  25%|██▌       | 1082/4257 [05:00<16:27,  3.21 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  25%|██▌       | 1083/4257 [05:00<14:49,  3.57 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  25%|██▌       | 1085/4257 [05:00<11:46,  4.49 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1595
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
EEEERRRRRRR 489
'>' not supported between instances of 'str' and 'float'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 651
index 0 is out of bounds for axis 0 with size 0
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 412
'age'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1424
invalid syntax (<string>, line 0)
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  26%|██▌       | 1087/4257 [05:01<17:26,  3.03 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  26%|██▌       | 1089/4257 [05:02<13:32,  3.90 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  26%|██▌       | 1090/4257 [05:02<12:48,  4.12 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  26%|██▌       | 1091/4257 [05:02<11:18,  4.67 examples/s]

EEEERRRRRRR 1275
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 930
Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'brazil scorers''str' object is not callable

'str' object is not callable

Map (num_proc=16):  26%|██▌       | 1092/4257 [05:02<13:25,  3.93 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 727
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
EEEERRRRRRR 561
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  26%|██▌       | 1094/4257 [05:03<16:24,  3.21 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  26%|██▌       | 1096/4257 [05:03<12:56,  4.07 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 251
'retired'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  26%|██▌       | 1097/4257 [05:04<14:51,  3.54 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  26%|██▌       | 1098/4257 [05:04<15:43,  3.35 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  26%|██▌       | 1099/4257 [05:04<13:18,  3.95 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  26%|██▌       | 1100/4257 [05:04<11:48,  4.46 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 'brazil scorers'331
'str' object is not callable

Can only use .dt accessor with datetimelike values

Map (num_proc=16):  26%|██▌       | 1101/4257 [05:05<12:47,  4.11 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR'brazil scorers'
1134'str' object is not callable

Map (num_proc=16):  26%|██▌       | 1103/4257 [05:05<14:24,  3.65 examples/s]

The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1595
'long row'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  26%|██▌       | 1104/4257 [05:06<16:19,  3.22 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  26%|██▌       | 1106/4257 [05:06<12:05,  4.35 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  26%|██▌       | 1107/4257 [05:06<13:33,  3.87 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 806
'time'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  26%|██▌       | 1108/4257 [05:06<12:50,  4.09 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  26%|██▌       | 1110/4257 [05:07<11:47,  4.45 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  26%|██▌       | 1111/4257 [05:07<11:20,  4.62 examples/s]

EEEERRRRRRR 490
'rank'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  26%|██▌       | 1112/4257 [05:07<11:41,  4.49 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 727
'>=' not supported between instances of 'str' and 'int'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 561
Can only use .dt accessor with datetimelike values
EEEERRRRRRR 1425
single positional indexer is out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 175
unsupported operand type(s) for -: 'str' and 'str'
EEEERRRRRRR

Map (num_proc=16):  26%|██▌       | 1113/4257 [05:08<18:18,  2.86 examples/s]

412
'>' not supported between instances of 'str' and 'int'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1596
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 930
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  26%|██▌       | 1115/4257 [05:09<19:14,  2.72 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 651
'school'
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  26%|██▌       | 1117/4257 [05:09<15:23,  3.40 examples/s]

EEEERRRRRRR 25
Can only use .dt accessor with datetimelike values
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  26%|██▋       | 1118/4257 [05:09<15:11,  3.44 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  26%|██▋       | 1119/4257 [05:10<13:54,  3.76 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 728
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR

Map (num_proc=16):  26%|██▋       | 1120/4257 [05:11<22:48,  2.29 examples/s]

 1276
'goals_conceded'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  26%|██▋       | 1121/4257 [05:11<21:03,  2.48 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 1134
'no'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 806
'time'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  26%|██▋       | 1122/4257 [05:11<23:27,  2.23 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  26%|██▋       | 1123/4257 [05:12<18:38,  2.80 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  26%|██▋       | 1124/4257 [05:12<17:03,  3.06 examples/s]

'brazil scorers'
'str' object is not callable
EEEERRRRRRR 90
could not convert string to float: ' degree20′53″'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  26%|██▋       | 1126/4257 [05:12<14:50,  3.52 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  26%|██▋       | 1128/4257 [05:13<13:05,  3.98 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 331
'>' not supported between instances of 'str' and 'Timestamp'
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 412
'nominations'

Map (num_proc=16):  27%|██▋       | 1131/4257 [05:13<13:24,  3.89 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 490
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 651
single positional indexer is out-of-bounds
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
EEEERRRRRRR 561
The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  27%|██▋       | 1132/4257 [05:14<17:32,  2.97 examples/s]

'brazil scorers'
'str' object is not callable
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5
'brazil scorers'
'str' object is not callable

Map (num_proc=16):  27%|██▋       | 1134/4257 [05:15<15:24,  3.38 examples/s]

Generating content with model: deepseek-ai/deepseek-coder-7b-instruct-v1.5

Map (num_proc=16):  27%|██▋       | 1135/4257 [05:15<14:24,  3.61 examples/s]

In [208]:
data = load_from_disk('tab_fact_test_xml_nlsep_correct/')

In [209]:
d2 = data.filter(lambda x : x['nlsep_answ_correct'] != 'None',num_proc=17)

In [210]:
d2

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'nlsep_answ', 'nlsep_label', 'nlsep_answ_correct', 'nlsep_label_correct'],
    num_rows: 471
})

In [179]:

data[0]

{'id': 0,
 'table_csv': '2-1570274-4.html.csv',
 'table_text': 'tournament#wins#top - 5#top - 10#top - 25#events#cuts made\nmasters tournament#0#1#2#4#4#4\nus open#0#2#3#4#6#5\nthe open championship#1#2#2#2#3#3\npga championship#0#0#1#2#5#4\ntotals#1#5#8#12#18#16\n',
 'label': 1,
 'statement': 'tony lema do not win in the us open',
 'table_caption': 'tony lema',
 'nlsep_query': 'tony lema do not win in the us open  col : tournament | wins | top - 5 | top - 10 | top - 25 | events | cuts made row 1 : masters tournament | 0 | 1 | 2 | 4 | 4 | 4 row 2 : us open | 0 | 2 | 3 | 4 | 6 | 5 row 3 : the open championship | 1 | 2 | 2 | 2 | 3 | 3 row 4 : pga championship | 0 | 0 | 1 | 2 | 5 | 4 row 5 : totals | 1 | 5 | 8 | 12 | 18 | 16',
 'semtab_query': 'tony lema do not win in the us open <TABLE><DESCRIPTION>tony lema</DESCRIPTION><HEADER><NAME>tournament</NAME><SEMANTIC_TYPE>category - 1.0</SEMANTIC_TYPE><DATA_TYPE>"str"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>["us open", "the open championship", "pga championship"]</EXAMPLES></HEADER><HEADER><NAME>wins</NAME><SEMANTIC_TYPE>rank - 1.0</SEMANTIC_TYPE><DATA_TYPE>"int"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>[0, 1, 0]</EXAMPLES></HEADER><HEADER><NAME>top - 5</NAME><SEMANTIC_TYPE>rank - 1.0</SEMANTIC_TYPE><DATA_TYPE>"int"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>[5, 2, 1]</EXAMPLES></HEADER><HEADER><NAME>top - 10</NAME><SEMANTIC_TYPE>rank - 1.0</SEMANTIC_TYPE><DATA_TYPE>"int"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>[8, 2, 1]</EXAMPLES></HEADER><HEADER><NAME>top - 25</NAME><SEMANTIC_TYPE>rank - 0.99</SEMANTIC_TYPE><DATA_TYPE>"int"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>[4, 12, 4]</EXAMPLES></HEADER><HEADER><NAME>events</NAME><SEMANTIC_TYPE>duration - 0.73</SEMANTIC_TYPE><DATA_TYPE>"int"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>[6, 4, 18]</EXAMPLES></HEADER><HEADER><NAME>cuts made</NAME><SEMANTIC_TYPE>rank - 0.99</SEMANTIC_TYPE><DATA_TYPE>"int"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>[4, 3, 5]</EXAMPLES></HEADER></TABLE>',
 'nlsep_answ': 'Here is the Python code that translates the given natural language statement into a single-line pandas expression. This expression checks if Tony Lema did not win in the US Open.\n\n```json\n"PANDA": "df.loc[df[\'tournament\'] == \'us open\', \'wins\'].any().tolist() == 0"\n```\n\nThis code first locates the row where the \'tournament\' column is \'us open\', and then checks if the \'wins\' column in that row is 0. If it is, the expression returns True, otherwise it returns False.\n',
 'nlsep_label': 'True',
 'nlsep_answ_correct': 'None'}

In [240]:
eval(parse_panda_code(d2[0]['nlsep_answ']))

KeyError: 'tournament'

# Traceback

In [243]:
import traceback

In [248]:
d2[0]

{'id': 0,
 'table_csv': '2-1570274-4.html.csv',
 'table_text': 'tournament#wins#top - 5#top - 10#top - 25#events#cuts made\nmasters tournament#0#1#2#4#4#4\nus open#0#2#3#4#6#5\nthe open championship#1#2#2#2#3#3\npga championship#0#0#1#2#5#4\ntotals#1#5#8#12#18#16\n',
 'label': 0,
 'statement': 'tournament that tony lema have not participate in include the master tournament , the us open , the pga championship and the open championship',
 'table_caption': 'tony lema',
 'nlsep_query': 'tournament that tony lema have not participate in include the master tournament , the us open , the pga championship and the open championship  col : tournament | wins | top - 5 | top - 10 | top - 25 | events | cuts made row 1 : masters tournament | 0 | 1 | 2 | 4 | 4 | 4 row 2 : us open | 0 | 2 | 3 | 4 | 6 | 5 row 3 : the open championship | 1 | 2 | 2 | 2 | 3 | 3 row 4 : pga championship | 0 | 0 | 1 | 2 | 5 | 4 row 5 : totals | 1 | 5 | 8 | 12 | 18 | 16',
 'semtab_query': 'tournament that tony lema have not participate in include the master tournament , the us open , the pga championship and the open championship <TABLE><DESCRIPTION>tony lema</DESCRIPTION><HEADER><NAME>tournament</NAME><SEMANTIC_TYPE>category - 1.0</SEMANTIC_TYPE><DATA_TYPE>"str"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>["us open", "totals", "masters tournament"]</EXAMPLES></HEADER><HEADER><NAME>wins</NAME><SEMANTIC_TYPE>rank - 1.0</SEMANTIC_TYPE><DATA_TYPE>"int"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>[0, 1, 0]</EXAMPLES></HEADER><HEADER><NAME>top - 5</NAME><SEMANTIC_TYPE>rank - 1.0</SEMANTIC_TYPE><DATA_TYPE>"int"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>[2, 2, 1]</EXAMPLES></HEADER><HEADER><NAME>top - 10</NAME><SEMANTIC_TYPE>rank - 1.0</SEMANTIC_TYPE><DATA_TYPE>"int"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>[3, 8, 1]</EXAMPLES></HEADER><HEADER><NAME>top - 25</NAME><SEMANTIC_TYPE>rank - 0.99</SEMANTIC_TYPE><DATA_TYPE>"int"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>[4, 4, 12]</EXAMPLES></HEADER><HEADER><NAME>events</NAME><SEMANTIC_TYPE>duration - 0.73</SEMANTIC_TYPE><DATA_TYPE>"int"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>[6, 5, 4]</EXAMPLES></HEADER><HEADER><NAME>cuts made</NAME><SEMANTIC_TYPE>rank - 0.99</SEMANTIC_TYPE><DATA_TYPE>"int"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>[4, 16, 4]</EXAMPLES></HEADER></TABLE>',
 'nlsep_answ': 'Here is the Python code in pandas that verifies the statement:\n\n```json\n"PANDA": "df[df[\'tournament\'].isin([\'the master tournament\', \'the us open\', \'the pga championship\', \'the open championship\']) & (df[\'participant\'] != \'tony lema\')].empty"\n```\n\nThis code checks if there are any rows in the dataframe where the tournament is in the list of tournaments and the participant is not Tony LeMa. If there are no such rows, it returns True, otherwise it returns False.\n',
 'nlsep_label': 'None',
 'nlsep_answ_correct': 'The error in the code is that the \'participant\' column does not exist in the dataframe. The correct column to check is \'wins\'. Here is the corrected code:\n\n```python\ndf[df[\'tournament\'].isin([\'the master tournament\', \'the us open\', \'the pga championship\', \'the open championship\']) & (df[\'wins\'] == 0)].empty\n```\n\nThis code checks if there are any rows in the dataframe where the \'tournament\' column is in the given list and the \'wins\' column is 0. If there are no such rows, it returns True, otherwise it returns False.\n\nHere is the Json Format:\n\n```json\n{\n    "CORRECT PANDA": "df[df[\'tournament\'].isin([\'the master tournament\', \'the us open\', \'the pga championship\', \'the open championship\']) & (df[\'wins\'] == 0)].empty"\n}\n```\n',
 'nlsep_label_correct': 'True'}

In [249]:
df = pd.read_csv(StringIO(d2[0]['table_text']), delimiter='#')
df

              tournament  wins  top - 5  top - 10  top - 25  events  cuts made
0     masters tournament     0        1         2         4       4          4
1                us open     0        2         3         4       6          5
2  the open championship     1        2         2         2       3          3
3       pga championship     0        0         1         2       5          4
4                 totals     1        5         8        12      18         16

In [246]:
parse_panda_code(d2[0]['nlsep_answ'])

"df[df['tournament'].isin(['the master tournament', 'the us open', 'the pga championship', 'the open championship']) & (df['participant'] != 'tony lema')].empty"

In [292]:
try:
    p=parse_panda_code(d2[0]['nlsep_answ'])
    eval(p)
except Exception as e:
    print (f'{type(e).__name__}: {e}')
    
    #traceback.print_exc()
    x = traceback.format_exc()
    #print(x)

KeyError: 'participant'

In [301]:
p = df.info

In [318]:
p = df.dtypes

In [319]:
p = p.to_string()

In [322]:
print(p)

tournament    object
wins           int64
top - 5        int64
top - 10       int64
top - 25       int64
events         int64
cuts made      int64

In [194]:
parse_panda_code(d2[2]['nlsep_answ_correct'])

"df['total'].isin([df.loc[df['player'] == 'matías suárez', 'total'].values[0] + 4]).any()"

In [180]:
d2[0]

{'id': 12,
 'table_csv': '2-13135264-6.html.csv',
 'table_text': 'date#visitor#score#home#decision#attendance#record\njanuary 2#detroit#4 - 1#carolina#joseph#17053#24 - 12 - 4 - 1\njanuary 3#anaheim#1 - 3#detroit#legace#20066#25 - 12 - 4 - 1\njanuary 5#nashville#0 - 6#detroit#joseph#20066#26 - 12 - 4 - 1\njanuary 7#boston#3 - 0#detroit#joseph#20066#26 - 13 - 4 - 1\njanuary 10#detroit#1 - 2#boston#joseph#17565#26 - 13 - 4 - 2\njanuary 14#chicago#2 - 4#detroit#legace#20066#27 - 13 - 4 - 2\njanuary 16#phoenix#3 - 3#detroit#joseph#20066#27 - 13 - 5 - 2\njanuary 19#detroit#1 - 2#san jose#joseph#17361#27 - 14 - 5 - 2\njanuary 21#detroit#2 - 2#anaheim#legace#17174#27 - 14 - 6 - 2\njanuary 22#detroit#5 - 4#los angeles#joseph#18118#28 - 14 - 6 - 2\njanuary 24#detroit#2 - 5#phoenix#joseph#19019#28 - 15 - 6 - 2\njanuary 26#detroit#2 - 2#dallas#legace#18532#28 - 15 - 7 - 2\njanuary 29#new jersey#2 - 5#detroit#joseph#20066#29 - 15 - 7 - 2\njanuary 31#carolina#4 - 4#detroit#legace#20066#30 - 15 - 8 - 2\n',
 'label': 0,
 'statement': 'there be a tie for the largest point gap 2 time during the season',
 'table_caption': '2003 - 04 detroit red wings season',
 'nlsep_query': 'there be a tie for the largest point gap 2 time during the season  col : date | visitor | score | home | decision | attendance | record row 1 : january 2 | detroit | 4 - 1 | carolina | joseph | 17053 | 24 - 12 - 4 - 1 row 2 : january 3 | anaheim | 1 - 3 | detroit | legace | 20066 | 25 - 12 - 4 - 1 row 3 : january 5 | nashville | 0 - 6 | detroit | joseph | 20066 | 26 - 12 - 4 - 1 row 4 : january 7 | boston | 3 - 0 | detroit | joseph | 20066 | 26 - 13 - 4 - 1 row 5 : january 10 | detroit | 1 - 2 | boston | joseph | 17565 | 26 - 13 - 4 - 2 row 6 : january 14 | chicago | 2 - 4 | detroit | legace | 20066 | 27 - 13 - 4 - 2 row 7 : january 16 | phoenix | 3 - 3 | detroit | joseph | 20066 | 27 - 13 - 5 - 2 row 8 : january 19 | detroit | 1 - 2 | san jose | joseph | 17361 | 27 - 14 - 5 - 2 row 9 : january 21 | detroit | 2 - 2 | anaheim | legace | 17174 | 27 - 14 - 6 - 2 row 10 : january 22 | detroit | 5 - 4 | los angeles | joseph | 18118 | 28 - 14 - 6 - 2 row 11 : january 24 | detroit | 2 - 5 | phoenix | joseph | 19019 | 28 - 15 - 6 - 2 row 12 : january 26 | detroit | 2 - 2 | dallas | legace | 18532 | 28 - 15 - 7 - 2 row 13 : january 29 | new jersey | 2 - 5 | detroit | joseph | 20066 | 29 - 15 - 7 - 2 row 14 : january 31 | carolina | 4 - 4 | detroit | legace | 20066 | 30 - 15 - 8 - 2',
 'semtab_query': 'there be a tie for the largest point gap 2 time during the season <TABLE><DESCRIPTION>2003 - 04 detroit red wings season</DESCRIPTION><HEADER><NAME>date</NAME><SEMANTIC_TYPE>day - 0.96</SEMANTIC_TYPE><DATA_TYPE>"str"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>["january 19", "january 3", "january 26"]</EXAMPLES></HEADER><HEADER><NAME>visitor</NAME><SEMANTIC_TYPE>city - 0.96</SEMANTIC_TYPE><DATA_TYPE>"str"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>["boston", "detroit", "detroit"]</EXAMPLES></HEADER><HEADER><NAME>score</NAME><SEMANTIC_TYPE>weight - 0.59</SEMANTIC_TYPE><DATA_TYPE>"str"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>["3 - 0", "1 - 2", "2 - 5"]</EXAMPLES></HEADER><HEADER><NAME>home</NAME><SEMANTIC_TYPE>team - 1.0</SEMANTIC_TYPE><DATA_TYPE>"str"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>["detroit", "san jose", "detroit"]</EXAMPLES></HEADER><HEADER><NAME>decision</NAME><SEMANTIC_TYPE>name - 1.0</SEMANTIC_TYPE><DATA_TYPE>"str"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>["joseph", "legace", "joseph"]</EXAMPLES></HEADER><HEADER><NAME>attendance</NAME><SEMANTIC_TYPE>depth - 0.85</SEMANTIC_TYPE><DATA_TYPE>"int"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>[20066, 17174, 17361]</EXAMPLES></HEADER><HEADER><NAME>record</NAME><SEMANTIC_TYPE>age - 0.88</SEMANTIC_TYPE><DATA_TYPE>"str"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>["28 - 15 - 7 - 2", "26 - 13 - 4 - 2", "25 - 12 - 4 - 1"]</EXAMPLES></HEADER></TABLE>',
 'nlsep_answ': '```json\n"PANDA": "df.groupby([\'home\', \'visitor\'])[\'score\'].apply(lambda x: x.str.split(\'-\', expand=True).apply(lambda y: abs(int(y[0]) - int(y[1])), axis=1).max().nlargest(2).index.duplicated().any()"\n```\nThis code groups the DataFrame by \'home\' and \'visitor\' columns, then for each group it calculates the maximum point gap between the scores. It then checks if there are any duplicated values in the top 2 maximum point gaps, indicating a tie.\n',
 'nlsep_label': 'False',
 'nlsep_answ_correct': 'The error in the code is due to an unbalanced parentheses. Here is the corrected code:\n\n```python\npandas_code = "(df[\'score\'].str.split(\'-\', expand=True)[0].astype(int) - df[\'score\'].str.split(\'-\', expand=True)[1].astype(int)).nunique() == 2"\n```\n\nThis code calculates the point gap between the home and visitor scores and checks if there are two unique values, which would indicate a tie for the largest point gap twice during the season.\n\nPlease note that the pandas_code must be a boolean. To ensure this, you can wrap the expression in a bool() function:\n\n```python\npandas_code = "bool((df[\'score\'].str.split(\'-\', expand=True)[0].astype(int) - df[\'score\'].str.split(\'-\', expand=True)[1].astype(int)).nunique() == 2)"\n```\n\nNow, when you run `str(bool(eval(pandas_code)))`, it should return `True` if there are two unique largest point gap values and `False` otherwise.\n\nPlease note that using `eval` can be dangerous if the input is not trusted, as it can execute any Python code. In this case, it is safe to use because the pandas_code is being constructed manually and not derived from user input.\n\nThe output in the Json format will be:\n\n```json\n{\n  "CORRECT PANDA": "bool((df[\'score\'].str.split(\'-\', expand=True)[0].astype(int) - df[\'score\'].str.split(\'-\', expand=True)[1].astype(int)).nunique() == 2)"\n}\n```\n'}

In [196]:
d3 = d2.filter(lambda x : x['nlsep_label'] != 'None',num_proc=17)

Filter (num_proc=17): 100%|██████████| 471/471 [00:00<00:00, 974.02 examples/s]

In [197]:
d3

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'nlsep_answ', 'nlsep_label', 'nlsep_answ_correct', 'nlsep_label_correct'],
    num_rows: 0
})

In [200]:
d3 = d2.filter(lambda x : x['nlsep_label_correct']==str(bool(x['label'])),num_proc=17)

Filter (num_proc=17): 100%|██████████| 471/471 [00:00<00:00, 918.59 examples/s]

In [201]:
d3

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'nlsep_answ', 'nlsep_label', 'nlsep_answ_correct', 'nlsep_label_correct'],
    num_rows: 296
})

In [205]:
df.dtypes

date              object
result            object
score             object
brazil scorers    object
competition       object
dtype: object

In [204]:
for col in df.columns:
    try:
        df[col] = pd.to_numeric(df[col])
    except ValueError:
        # Если возникает ошибка, оставляем столбец как есть
        pass

In [206]:
df

,date,result,score,brazil scorers,competition
0,"may 11 , 1919",w,6 - 0,"friedenreich (3) , neco (2) , haroldo",south american championship
1,"may 18 , 1919",w,3 - 1,"heitor , amílcar , millon",south american championship
2,"may 26 , 1919",d,2 - 2,neco (2),south american championship
3,"may 29 , 1919",w,1 - 0,friedenreich,south american championship
4,"june 1 , 1919",d,3 - 3,"haroldo , arlindo (2)",taça roberto cherry

In [212]:
data = load_from_disk('tab_fact_test_xml_nlsep_correct_dtype/')
d2 = data.filter(lambda x : x['nlsep_answ_correct'] != 'None',num_proc=17)

Filter (num_proc=17): 100%|██████████| 4257/4257 [00:00<00:00, 8874.34 examples/s]

In [213]:
d2

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'nlsep_answ', 'nlsep_label', 'nlsep_answ_correct', 'nlsep_label_correct'],
    num_rows: 415
})

In [214]:
process_data = load_from_disk('./tab_fact_test_xml_nlsep_new_correct//')
print(process_data)
dd = process_data.filter(lambda x: True if x['nlsep_answ']!='None' else False,num_proc=17)
print(dd)
dd = process_data.filter(lambda x: True if x['nlsep_label']!='None' else False,num_proc=17)
print(dd)
print(dd.shape[0]/process_data.shape[0]*100)
true = dd.filter(lambda x : True if x['nlsep_label']==str(bool(x['label'])) else False,num_proc=17)
print(true.shape[0]/process_data.shape[0]*100)

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'nlsep_answ', 'nlsep_label', 'nlsep_answ_correct'],
    num_rows: 12779
})

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:00<00:00, 27151.13 examples/s]

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'nlsep_answ', 'nlsep_label', 'nlsep_answ_correct'],
    num_rows: 12779
})

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:00<00:00, 25923.24 examples/s]

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'nlsep_answ', 'nlsep_label', 'nlsep_answ_correct'],
    num_rows: 8974
})
70.22458721339699

Filter (num_proc=17): 100%|██████████| 8974/8974 [00:00<00:00, 18914.21 examples/s]

42.92980671414038

In [217]:
dd[0]

{'id': 0,
 'table_csv': '2-1570274-4.html.csv',
 'table_text': 'tournament#wins#top - 5#top - 10#top - 25#events#cuts made\nmasters tournament#0#1#2#4#4#4\nus open#0#2#3#4#6#5\nthe open championship#1#2#2#2#3#3\npga championship#0#0#1#2#5#4\ntotals#1#5#8#12#18#16\n',
 'label': 1,
 'statement': 'tournament that tony lema have participate in include the master tournament , the us open , the pga championship and the open championship',
 'table_caption': 'tony lema',
 'nlsep_query': 'tournament that tony lema have participate in include the master tournament , the us open , the pga championship and the open championship  col : tournament | wins | top - 5 | top - 10 | top - 25 | events | cuts made row 1 : masters tournament | 0 | 1 | 2 | 4 | 4 | 4 row 2 : us open | 0 | 2 | 3 | 4 | 6 | 5 row 3 : the open championship | 1 | 2 | 2 | 2 | 3 | 3 row 4 : pga championship | 0 | 0 | 1 | 2 | 5 | 4 row 5 : totals | 1 | 5 | 8 | 12 | 18 | 16',
 'semtab_query': 'tournament that tony lema have participate in include the master tournament , the us open , the pga championship and the open championship <TABLE><DESCRIPTION>tony lema</DESCRIPTION><HEADER><NAME>tournament</NAME><SEMANTIC_TYPE>category - 1.0</SEMANTIC_TYPE><DATA_TYPE>"str"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>["pga championship", "masters tournament", "us open"]</EXAMPLES></HEADER><HEADER><NAME>wins</NAME><SEMANTIC_TYPE>rank - 1.0</SEMANTIC_TYPE><DATA_TYPE>"int"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>[0, 0, 0]</EXAMPLES></HEADER><HEADER><NAME>top - 5</NAME><SEMANTIC_TYPE>rank - 1.0</SEMANTIC_TYPE><DATA_TYPE>"int"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>[2, 5, 2]</EXAMPLES></HEADER><HEADER><NAME>top - 10</NAME><SEMANTIC_TYPE>rank - 1.0</SEMANTIC_TYPE><DATA_TYPE>"int"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>[8, 1, 3]</EXAMPLES></HEADER><HEADER><NAME>top - 25</NAME><SEMANTIC_TYPE>rank - 0.99</SEMANTIC_TYPE><DATA_TYPE>"int"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>[12, 2, 4]</EXAMPLES></HEADER><HEADER><NAME>events</NAME><SEMANTIC_TYPE>duration - 0.73</SEMANTIC_TYPE><DATA_TYPE>"int"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>[18, 5, 6]</EXAMPLES></HEADER><HEADER><NAME>cuts made</NAME><SEMANTIC_TYPE>rank - 0.99</SEMANTIC_TYPE><DATA_TYPE>"int"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>[5, 3, 16]</EXAMPLES></HEADER></TABLE>',
 'nlsep_answ': 'Here is the single-line pandas expression that translates the given natural language statement:\n\n```json\n"PANDA": "df[(df[\'tournament\'] == \'tony lema\') & (df[\'tournament\'].isin([\'the master tournament\', \'the us open\', \'the pga championship\', \'the open championship\']))].sum().eq(df.loc[4]).all()"\n```\n\nThis expression checks if the sum of the specified columns for the rows where \'tournament\' is \'tony lema\' and where \'tournament\' is in the given list of tournaments equals the sum of the specified columns for the total row.\n',
 'nlsep_label': 'False',
 'nlsep_answ_correct': 'None'}

In [216]:
process_data.filter(lambda x: True if x['nlsep_answ_correct']!='None' else False,num_proc=17)

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:00<00:00, 26475.69 examples/s]

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'nlsep_answ', 'nlsep_label', 'nlsep_answ_correct'],
    num_rows: 479
})

In [220]:
process_data.filter(lambda x: True if x['id']==905 else False,num_proc=17)[0]

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:00<00:00, 26537.53 examples/s]

{'id': 905,
 'table_csv': '2-17231125-6.html.csv',
 'table_text': "place#player#country#score#to par\n1#curtis strange#united states#70 + 67 + 69 = 206#- 7\nt2#nick faldo#england#72 + 67 + 68 = 207#- 6\nt2#bob gilder#united states#68 + 69 + 70 = 207#- 6\nt2#scott simpson#united states#69 + 66 + 72 = 207#- 6\nt5#larry mize#united states#69 + 67 + 72 = 208#- 5\nt5#d a weibring#united states#71 + 69 + 68 = 208#- 5\n7#mark o'meara#united states#71 + 72 + 66 = 209#- 4\n8#fred couples#united states#72 + 67 + 71 = 210#- 3\n9#lanny wadkins#united states#70 + 71 + 70 = 211#- 2\n10#ken green#united states#72 + 70 + 70 = 212#- 1\n",
 'label': 1,
 'statement': 'player larry mize and d a be tie for 5th place',
 'table_caption': '1988 u.s. open (golf)',
 'nlsep_query': "player larry mize and d a be tie for 5th place  col : place | player | country | score | to par row 1 : 1 | curtis strange | united states | 70 + 67 + 69 = 206 | - 7 row 2 : t2 | nick faldo | england | 72 + 67 + 68 = 207 | - 6 row 3 : t2 | bob gilder | united states | 68 + 69 + 70 = 207 | - 6 row 4 : t2 | scott simpson | united states | 69 + 66 + 72 = 207 | - 6 row 5 : t5 | larry mize | united states | 69 + 67 + 72 = 208 | - 5 row 6 : t5 | d a weibring | united states | 71 + 69 + 68 = 208 | - 5 row 7 : 7 | mark o'meara | united states | 71 + 72 + 66 = 209 | - 4 row 8 : 8 | fred couples | united states | 72 + 67 + 71 = 210 | - 3 row 9 : 9 | lanny wadkins | united states | 70 + 71 + 70 = 211 | - 2 row 10 : 10 | ken green | united states | 72 + 70 + 70 = 212 | - 1",
 'semtab_query': 'player larry mize and d a be tie for 5th place <TABLE><DESCRIPTION>1988 u.s. open (golf)</DESCRIPTION><HEADER><NAME>place</NAME><SEMANTIC_TYPE>rank - 1.0</SEMANTIC_TYPE><DATA_TYPE>"int"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>["t2", "t5", "7"]</EXAMPLES></HEADER><HEADER><NAME>player</NAME><SEMANTIC_TYPE>name - 1.0</SEMANTIC_TYPE><DATA_TYPE>"str"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>["scott simpson", "lanny wadkins", "bob gilder"]</EXAMPLES></HEADER><HEADER><NAME>country</NAME><SEMANTIC_TYPE>nationality - 1.0</SEMANTIC_TYPE><DATA_TYPE>"str"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>["united states", "united states", "united states"]</EXAMPLES></HEADER><HEADER><NAME>score</NAME><SEMANTIC_TYPE>weight - 1.0</SEMANTIC_TYPE><DATA_TYPE>"str"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>["72 + 70 + 70 = 212", "71 + 69 + 68 = 208", "70 + 67 + 69 = 206"]</EXAMPLES></HEADER><HEADER><NAME>to par</NAME><SEMANTIC_TYPE>weight - 0.71</SEMANTIC_TYPE><DATA_TYPE>"str"</DATA_TYPE><HAS_NONE>0</HAS_NONE><EXAMPLES>["- 6", "- 5", "- 6"]</EXAMPLES></HEADER></TABLE>',
 'nlsep_answ': 'Here\'s the single-line pandas expression:\n\n```json\n"PANDA": "df.loc[df[\'score\'].isin(df.loc[df[\'place\']==5, \'score\']), \'player\'].str.contains(\'larry mize|d a weibring\').all()"\n```\n\nThis expression checks if all the players in the 5th place score are present in the score of \'larry mize\' and \'d a weibring\'.\n',
 'nlsep_label': 'True',
 'nlsep_answ_correct': 'None'}

In [221]:
parse_panda_code('Here\'s the single-line pandas expression:\n\n```json\n"PANDA": "df.loc[df[\'score\'].isin(df.loc[df[\'place\']==5, \'score\']), \'player\'].str.contains(\'larry mize|d a weibring\').all()"\n```\n\nThis expression checks if all the players in the 5th place score are present in the score of \'larry mize\' and \'d a weibring\'.\n')

"df.loc[df['score'].isin(df.loc[df['place']==5, 'score']), 'player'].str.contains('larry mize|d a weibring').all()"

In [237]:
df = pd.read_csv(StringIO("place#player#country#score#to par\n1#curtis strange#united states#70 + 67 + 69 = 206#- 7\nt2#nick faldo#england#72 + 67 + 68 = 207#- 6\nt2#bob gilder#united states#68 + 69 + 70 = 207#- 6\nt2#scott simpson#united states#69 + 66 + 72 = 207#- 6\nt5#larry mize#united states#69 + 67 + 72 = 208#- 5\nt5#d a weibring#united states#71 + 69 + 68 = 208#- 5\n7#mark o'meara#united states#71 + 72 + 66 = 209#- 4\n8#fred couples#united states#72 + 67 + 71 = 210#- 3\n9#lanny wadkins#united states#70 + 71 + 70 = 211#- 2\n10#ken green#united states#72 + 70 + 70 = 212#- 1\n"), delimiter='#')

In [238]:
df

  place          player        country               score to par
0     1  curtis strange  united states  70 + 67 + 69 = 206    - 7
1    t2      nick faldo        england  72 + 67 + 68 = 207    - 6
2    t2      bob gilder  united states  68 + 69 + 70 = 207    - 6
3    t2   scott simpson  united states  69 + 66 + 72 = 207    - 6
4    t5      larry mize  united states  69 + 67 + 72 = 208    - 5
5    t5    d a weibring  united states  71 + 69 + 68 = 208    - 5
6     7    mark o'meara  united states  71 + 72 + 66 = 209    - 4
7     8    fred couples  united states  72 + 67 + 71 = 210    - 3
8     9   lanny wadkins  united states  70 + 71 + 70 = 211    - 2
9    10       ken green  united states  72 + 70 + 70 = 212    - 1

In [239]:
df.dtypes

place      object
player     object
country    object
score      object
to par     object
dtype: object

In [230]:
for col in df.columns:
    try:
        df[col] = pd.to_numeric(df[col])
    except ValueError as e:
        print(col,e)
        # Если возникает ошибка, оставляем столбец как есть
        pass

place Unable to parse string "t2" at position 1
player Unable to parse string "curtis strange" at position 0
country Unable to parse string "united states" at position 0
score Unable to parse string "70 + 67 + 69 = 206" at position 0
to par Unable to parse string "- 7" at position 0

In [235]:
int('-7')

-7

In [236]:
eval("df.loc[df['score'].isin(df.loc[df['place']==5, 'score']), 'player'].str.contains('larry mize|d a weibring').all()")

np.True_

In [334]:
data = load_from_disk('tab_fact_test_xml_nlsep_new_correct_modify/')
print(data)
process_data = data.filter(lambda x : x['nlsep_answ_correct'] != 'None',num_proc=17)
print(process_data)
dd = process_data.filter(lambda x: True if x['nlsep_label']!='None' else False,num_proc=17)
print(dd.shape[0]/data.shape[0]*100)
print(dd.shape[0]/process_data.shape[0]*100)
true = dd.filter(lambda x : True if x['nlsep_label']==str(bool(x['label'])) else False,num_proc=17)
print(true.shape[0]/process_data.shape[0]*100)
full = data.filter(lambda x : True if x['nlsep_label']==str(bool(x['label'])) else False,num_proc=17)
print(full.shape[0]/data.shape[0]*100)

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'nlsep_answ', 'nlsep_label', 'nlsep_answ_correct'],
    num_rows: 12779
})
Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'nlsep_answ', 'nlsep_label', 'nlsep_answ_correct'],
    num_rows: 2798
})
21.89529697159402
100.0
57.255182273052185

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:00<00:00, 27316.22 examples/s]

55.450348227560845

In [329]:
true = dd.filter(lambda x : True if x['nlsep_label']==str(bool(x['label'])) else False,num_proc=17)

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'nlsep_answ', 'nlsep_label', 'nlsep_answ_correct'],
    num_rows: 2798
})

In [335]:
data = load_from_disk('tab_fact_test_xml_semtab_new_correct_modify/')
print(data)
process_data = data.filter(lambda x : x['semtab_answ_correct'] != 'None',num_proc=17)
print(process_data)
dd = process_data.filter(lambda x: True if x['semtab_label']!='None' else False,num_proc=17)
print(dd.shape[0]/data.shape[0]*100)
print(dd.shape[0]/process_data.shape[0]*100)
true = dd.filter(lambda x : True if x['semtab_label']==str(bool(x['label'])) else False,num_proc=17)
print(true.shape[0]/process_data.shape[0]*100)
full = data.filter(lambda x : True if x['semtab_label']==str(bool(x['label'])) else False,num_proc=17)
print(full.shape[0]/data.shape[0]*100)

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'semtab_answ', 'semtab_label', 'semtab_answ_correct'],
    num_rows: 12779
})

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:00<00:00, 25449.74 examples/s]

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'semtab_answ', 'semtab_label', 'semtab_answ_correct'],
    num_rows: 2727
})

Filter (num_proc=17): 100%|██████████| 2727/2727 [00:00<00:00, 5528.78 examples/s]

21.339697941935988
100.0

Filter (num_proc=17): 100%|██████████| 2727/2727 [00:00<00:00, 5716.06 examples/s]

54.49211587825449

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:00<00:00, 25739.32 examples/s]

51.85069254245246

In [327]:
df_info

'tournament    object\nwins           int64\ntop - 5        int64\ntop - 10       int64\ntop - 25       int64\nevents         int64\ncuts made      int64'

In [336]:
data = load_from_disk('tab_fact_test_xml_semtab_new_correct_modify_add_info/')
print(data)
process_data = data.filter(lambda x : x['semtab_answ_correct'] != 'None',num_proc=17)
print(process_data)
dd = process_data.filter(lambda x: True if x['semtab_label']!='None' else False,num_proc=17)
print(dd.shape[0]/data.shape[0]*100)
print(dd.shape[0]/process_data.shape[0]*100)
true = dd.filter(lambda x : True if x['semtab_label']==str(bool(x['label'])) else False,num_proc=17)
print(true.shape[0]/process_data.shape[0]*100)
full = data.filter(lambda x : True if x['semtab_label']==str(bool(x['label'])) else False,num_proc=17)
print(full.shape[0]/data.shape[0]*100)

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'semtab_answ', 'semtab_label', 'semtab_answ_correct'],
    num_rows: 12779
})

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:00<00:00, 25729.94 examples/s]

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'semtab_answ', 'semtab_label', 'semtab_answ_correct'],
    num_rows: 2876
})

Filter (num_proc=17): 100%|██████████| 2876/2876 [00:00<00:00, 5600.28 examples/s]

22.50567337037327
100.0

Filter (num_proc=17): 100%|██████████| 2876/2876 [00:00<00:00, 5845.32 examples/s]

54.24200278164116

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:00<00:00, 26336.59 examples/s]

52.81320917129666

In [337]:
data = load_from_disk('tab_fact_test_xml_nlsep_new_correct_modify_noadd_info/')
print(data)
process_data = data.filter(lambda x : x['nlsep_answ_correct'] != 'None',num_proc=17)
print(process_data)
dd = process_data.filter(lambda x: True if x['nlsep_label']!='None' else False,num_proc=17)
print(dd.shape[0]/data.shape[0]*100)
print(dd.shape[0]/process_data.shape[0]*100)
true = dd.filter(lambda x : True if x['nlsep_label']==str(bool(x['label'])) else False,num_proc=17)
print(true.shape[0]/process_data.shape[0]*100)
full = data.filter(lambda x : True if x['nlsep_label']==str(bool(x['label'])) else False,num_proc=17)
print(full.shape[0]/data.shape[0]*100)

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'nlsep_answ', 'nlsep_label', 'nlsep_answ_correct'],
    num_rows: 12779
})

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:00<00:00, 25537.02 examples/s]

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'nlsep_answ', 'nlsep_label', 'nlsep_answ_correct'],
    num_rows: 2747
})

Filter (num_proc=17): 100%|██████████| 2747/2747 [00:00<00:00, 5446.84 examples/s]

21.496204710853746
100.0

Filter (num_proc=17): 100%|██████████| 2747/2747 [00:00<00:00, 5683.92 examples/s]

58.79140880961048

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:00<00:00, 26767.75 examples/s]

54.229595430002355

In [340]:
print(df.to_string())

              tournament  wins  top - 5  top - 10  top - 25  events  cuts made
0     masters tournament     0        1         2         4       4          4
1                us open     0        2         3         4       6          5
2  the open championship     1        2         2         2       3          3
3       pga championship     0        0         1         2       5          4
4                 totals     1        5         8        12      18         16

In [341]:
data

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'nlsep_answ', 'nlsep_label', 'nlsep_answ_correct'],
    num_rows: 12779
})

In [342]:
data[0]['statement']

'tony lema be in the top 5 for the master tournament , the us open , and the open championship'

In [343]:
import yaml
def load_config(config_file_path):
    with open(config_file_path, 'r') as stream:
        try:
            # Use safe_load for security
            config = yaml.safe_load(stream)
            return config
        except yaml.YAMLError as exc:
            print(exc)

In [344]:
    config_data = load_config('convert_config.yaml')

In [347]:

config_data.keys()

dict_keys(['semtab_xml_elements'])

In [349]:
type(config_data['semtab_xml_elements']['include_data_types'])

bool

In [356]:
data = load_from_disk('tab_fact_test_universal2')

In [357]:
data

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'semtab_html_elements_semantic_datatype_exampples_description_top1_tresh50', 'semtab_xml_attributes_semantic_datatype_exampples_description_top1_tresh50', 'semtab_xml_elements_semantic_datatype_exampples_description_top1_tresh50', 'semtab_xml_elements_datatype_exampples_description_top1_tresh50', 'semtab_xml_elements_exampples_description_top1_tresh50', 'semtab_xml_elements_description_top1_tresh50'],
    num_rows: 12779
})

In [358]:
data[50]['semtab_html_elements_semantic_datatype_exampples_description_top1_tresh50']

'<table><caption>1989 u.s. open (golf)</caption><thead><tr><th SEMANTIC_TYPE="rank - 0.99" DATA_TYPE="&quot;str&quot;" HAS_NONE="0" EXAMPLES="[&quot;1&quot;, &quot;t6&quot;, &quot;t9&quot;]">place</th><th SEMANTIC_TYPE="name - 1.0" DATA_TYPE="&quot;str&quot;" HAS_NONE="0" EXAMPLES="[&quot;tom kite&quot;, &quot;brian claar&quot;, &quot;mark mccumber&quot;]">player</th><th SEMANTIC_TYPE="nationality - 1.0" DATA_TYPE="&quot;str&quot;" HAS_NONE="0" EXAMPLES="[&quot;united states&quot;, &quot;united states&quot;, &quot;spain&quot;]">country</th><th SEMANTIC_TYPE="weight - 0.91" DATA_TYPE="&quot;str&quot;" HAS_NONE="0" EXAMPLES="[&quot;70 + 68 + 73 + 68 = 279&quot;, &quot;71 + 70 + 71 + 70 = 282&quot;, &quot;70 + 71 + 68 + 72 = 281&quot;]">score</th><th SEMANTIC_TYPE="weight - 0.64" DATA_TYPE="&quot;str&quot;" HAS_NONE="0" EXAMPLES="[&quot;+ 1&quot;, &quot;+ 1&quot;, &quot;- 2&quot;]">to par</th><th SEMANTIC_TYPE="year - 0.97" DATA_TYPE="&quot;int&quot;" HAS_NONE="0" EXAMPLES="[200000, 28220, 24307]">money</th></tr></thead></table>'

In [360]:
data = load_from_disk('tab_fact_test_xml_space_new_correct_modify_noadd_info/')
print(data)
process_data = data.filter(lambda x : x['space_answ_correct'] != 'None',num_proc=17)
print(process_data)
dd = process_data.filter(lambda x: True if x['space_label']!='None' else False,num_proc=17)
print(dd.shape[0]/data.shape[0]*100)
print(dd.shape[0]/process_data.shape[0]*100)
true = dd.filter(lambda x : True if x['space_label']==str(bool(x['label'])) else False,num_proc=17)
print(true.shape[0]/process_data.shape[0]*100)
full = data.filter(lambda x : True if x['space_label']==str(bool(x['label'])) else False,num_proc=17)
print(full.shape[0]/data.shape[0]*100)

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'space_answ', 'space_label', 'space_answ_correct'],
    num_rows: 12779
})

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:00<00:00, 25156.65 examples/s]

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'nlsep_query', 'semtab_query', 'space_answ', 'space_label', 'space_answ_correct'],
    num_rows: 3026
})

Filter (num_proc=17): 100%|██████████| 3026/3026 [00:00<00:00, 5870.48 examples/s]

23.679474137256438
100.0

Filter (num_proc=17): 100%|██████████| 3026/3026 [00:00<00:00, 5859.72 examples/s]

56.2128222075347

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:00<00:00, 24946.84 examples/s]

53.28272947804993

In [361]:
tab_fact_test_semtab_html_elements_semantic_datatype_exampples_description_top1_tresh50_new_correct_modify_noadd_info

NameError: name 'tab_fact_test_semtab_html_elements_semantic_datatype_exampples_description_top1_tresh50_new_correct_modify_noadd_info' is not defined

In [362]:
data = load_from_disk('tab_fact_test_semtab_html_elements_semantic_datatype_exampples_description_top1_tresh50_new_correct_modify_noadd_info/')
print(data)
process_data = data.filter(lambda x : x['semtab_html_elements_semantic_datatype_exampples_description_top1_tresh50_answ_correct'] != 'None',num_proc=17)
print(process_data)
dd = process_data.filter(lambda x: True if x['semtab_html_elements_semantic_datatype_exampples_description_top1_tresh50_label']!='None' else False,num_proc=17)
print(dd.shape[0]/data.shape[0]*100)
print(dd.shape[0]/process_data.shape[0]*100)
true = dd.filter(lambda x : True if x['semtab_html_elements_semantic_datatype_exampples_description_top1_tresh50_label']==str(bool(x['label'])) else False,num_proc=17)
print(true.shape[0]/process_data.shape[0]*100)
full = data.filter(lambda x : True if x['semtab_html_elements_semantic_datatype_exampples_description_top1_tresh50_label']==str(bool(x['label'])) else False,num_proc=17)
print(full.shape[0]/data.shape[0]*100)

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'semtab_html_elements_semantic_datatype_exampples_description_top1_tresh50', 'semtab_xml_attributes_semantic_datatype_exampples_description_top1_tresh50', 'semtab_xml_elements_semantic_datatype_exampples_description_top1_tresh50', 'semtab_xml_elements_datatype_exampples_description_top1_tresh50', 'semtab_xml_elements_exampples_description_top1_tresh50', 'semtab_xml_elements_description_top1_tresh50', 'semtab_html_elements_semantic_datatype_exampples_description_top1_tresh50_answ', 'semtab_html_elements_semantic_datatype_exampples_description_top1_tresh50_label', 'semtab_html_elements_semantic_datatype_exampples_description_top1_tresh50_answ_correct'],
    num_rows: 12779
})

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:00<00:00, 25331.21 examples/s]

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'semtab_html_elements_semantic_datatype_exampples_description_top1_tresh50', 'semtab_xml_attributes_semantic_datatype_exampples_description_top1_tresh50', 'semtab_xml_elements_semantic_datatype_exampples_description_top1_tresh50', 'semtab_xml_elements_datatype_exampples_description_top1_tresh50', 'semtab_xml_elements_exampples_description_top1_tresh50', 'semtab_xml_elements_description_top1_tresh50', 'semtab_html_elements_semantic_datatype_exampples_description_top1_tresh50_answ', 'semtab_html_elements_semantic_datatype_exampples_description_top1_tresh50_label', 'semtab_html_elements_semantic_datatype_exampples_description_top1_tresh50_answ_correct'],
    num_rows: 2399
})

Filter (num_proc=17): 100%|██████████| 2399/2399 [00:00<00:00, 4543.86 examples/s]

18.772986931684795
100.0

Filter (num_proc=17): 100%|██████████| 2399/2399 [00:00<00:00, 4636.70 examples/s]

54.18924551896623

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:00<00:00, 24993.23 examples/s]

53.86180452304562

| Method              | Accuracy |
|---------------------|:--------:|
| semtab xml elements |   51.85  |
| semtab html         |   53.86  |
| space               |   53.28  |
| nlsep               |   54.23  |

In [364]:
df.to_markdown()

'|    | tournament            |   wins |   top - 5 |   top - 10 |   top - 25 |   events |   cuts made |\n|---:|:----------------------|-------:|----------:|-----------:|-----------:|---------:|------------:|\n|  0 | masters tournament    |      0 |         1 |          2 |          4 |        4 |           4 |\n|  1 | us open               |      0 |         2 |          3 |          4 |        6 |           5 |\n|  2 | the open championship |      1 |         2 |          2 |          2 |        3 |           3 |\n|  3 | pga championship      |      0 |         0 |          1 |          2 |        5 |           4 |\n|  4 | totals                |      1 |         5 |          8 |         12 |       18 |          16 |'

In [ ]:
python abation_experiments.py --inputdata tab_fact_test_semtab_html_ablation_correcring --outputdata tab_fact_test_semtab_html_ablation_correcring --conf-file semtab_html_config_answer2.yaml --num_proc 16 > correct_tabfact_semtab_html_log2.txt

In [365]:
import torch

In [367]:
str(torch.device('cuda'))

'cuda'

In [371]:
data = load_from_disk('tab_fact_test_semtab_html_ablation/')

In [372]:
data

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'semtab_html_semantic_datatype_exampples3_description_top1_tresh50', 'semtab_html_datatype_exampples3_description_top1_tresh50', 'semtab_html_exampples3_description_top1_tresh50', 'semtab_html_description_top1_tresh50', 'semtab_html_top1_tresh50'],
    num_rows: 12779
})

In [374]:
data[0]['semtab_html_top1_tresh50']

'<table><thead><tr><th>tournament</th><th>wins</th><th>top - 5</th><th>top - 10</th><th>top - 25</th><th>events</th><th>cuts made</th></tr></thead></table>'

# Ablation study

In [376]:
from datasets import load_from_disk

In [381]:
data = load_from_disk("tab_fact_test_semtab_html_ablation_correcring_first_new")

In [382]:
data

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'semtab_html_semantic_datatype_exampples3_description_top1_tresh50', 'semtab_html_datatype_exampples3_description_top1_tresh50', 'semtab_html_exampples3_description_top1_tresh50', 'semtab_html_description_top1_tresh50', 'semtab_html_top1_tresh50', 'semtab_html_semantic_datatype_exampples3_description_top1_tresh50_answ', 'semtab_html_semantic_datatype_exampples3_description_top1_tresh50_label', 'semtab_html_semantic_datatype_exampples3_description_top1_tresh50_answ_correct', 'semtab_html_datatype_exampples3_description_top1_tresh50_answ', 'semtab_html_datatype_exampples3_description_top1_tresh50_label', 'semtab_html_datatype_exampples3_description_top1_tresh50_answ_correct', 'semtab_html_exampples3_description_top1_tresh50_answ', 'semtab_html_exampples3_description_top1_tresh50_label', 'semtab_html_exampples3_description_top1_tresh50_answ_correct', 'semtab_html_description_top1_tresh50_answ', 'semtab_html_description_top1_tresh50_label', 'semtab_html_description_top1_tresh50_answ_correct', 'semtab_html_top1_tresh50_answ', 'semtab_html_top1_tresh50_label', 'semtab_html_top1_tresh50_answ_correct'],
    num_rows: 12779
})

In [383]:
from utils.utils import load_config

In [384]:
config = load_config('semtab_html_config_answer2.yaml')

In [386]:
tests = list(config.keys())
tests

['semtab_html_semantic_datatype_exampples3_description_top1_tresh50',
 'semtab_html_datatype_exampples3_description_top1_tresh50',
 'semtab_html_exampples3_description_top1_tresh50',
 'semtab_html_description_top1_tresh50',
 'semtab_html_top1_tresh50']

In [391]:
acc_old = None
for test in tests:
    print(test)
    process_data = data.filter(lambda x : x[f'{test}_answ_correct'] != 'None',num_proc=17)
    dd = process_data.filter(lambda x: True if x[f'{test}_label']!='None' else False,num_proc=17)
    #print(dd.shape[0]/data.shape[0]*100)
    #print(dd.shape[0]/process_data.shape[0]*100)
    true = dd.filter(lambda x : True if x[f'{test}_label']==str(bool(x['label'])) else False,num_proc=17)
    #print(true.shape[0]/process_data.shape[0]*100)
    full = data.filter(lambda x : True if x[f'{test}_label']==str(bool(x['label'])) else False,num_proc=17)
    acc = full.shape[0]/data.shape[0]*100
    print(acc)
    if acc_old == None:
        acc_old = acc
    print('different',acc-acc_old)
    acc_old = acc

semtab_html_semantic_datatype_exampples3_description_top1_tresh50
53.673996400344315
different 0.0
semtab_html_datatype_exampples3_description_top1_tresh50
54.816495813443936
different 1.142499413099621
semtab_html_exampples3_description_top1_tresh50
54.11221535331403
different -0.7042804601299082
semtab_html_description_top1_tresh50
46.545113076140545
different -7.567102277173483
semtab_html_top1_tresh50
46.490335707019334
different -0.05477736912121145

In [392]:
data

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'semtab_html_semantic_datatype_exampples3_description_top1_tresh50', 'semtab_html_datatype_exampples3_description_top1_tresh50', 'semtab_html_exampples3_description_top1_tresh50', 'semtab_html_description_top1_tresh50', 'semtab_html_top1_tresh50', 'semtab_html_semantic_datatype_exampples3_description_top1_tresh50_answ', 'semtab_html_semantic_datatype_exampples3_description_top1_tresh50_label', 'semtab_html_semantic_datatype_exampples3_description_top1_tresh50_answ_correct', 'semtab_html_datatype_exampples3_description_top1_tresh50_answ', 'semtab_html_datatype_exampples3_description_top1_tresh50_label', 'semtab_html_datatype_exampples3_description_top1_tresh50_answ_correct', 'semtab_html_exampples3_description_top1_tresh50_answ', 'semtab_html_exampples3_description_top1_tresh50_label', 'semtab_html_exampples3_description_top1_tresh50_answ_correct', 'semtab_html_description_top1_tresh50_answ', 'semtab_html_description_top1_tresh50_label', 'semtab_html_description_top1_tresh50_answ_correct', 'semtab_html_top1_tresh50_answ', 'semtab_html_top1_tresh50_label', 'semtab_html_top1_tresh50_answ_correct'],
    num_rows: 12779
})

In [394]:
print(data[0]['table_text'])

tournament#wins#top - 5#top - 10#top - 25#events#cuts made
masters tournament#0#1#2#4#4#4
us open#0#2#3#4#6#5
the open championship#1#2#2#2#3#3
pga championship#0#0#1#2#5#4
totals#1#5#8#12#18#16

In [395]:
data2 = dataset.to_pandas()

In [396]:
data2

,id,statement,label,table_caption,table_text,pandas_code,pandas_eval,nlsep_query,semtab_query
0,0,haroldo be mention as a brazil scorer for 2 di...,1,1919 in brazilian football,date#result#score#brazil scorers#competition\n...,df['brazil scorers'].apply(lambda x: 'haroldo'...,True,haroldo be mention as a brazil scorer for 2 di...,haroldo be mention as a brazil scorer for 2 di...
1,1,4 of the 5 game be for the south american cham...,1,1919 in brazilian football,date#result#score#brazil scorers#competition\n...,(df['competition'].value_counts()['south ameri...,True,4 of the 5 game be for the south american cham...,4 of the 5 game be for the south american cham...
2,2,friedenreich be mention as a brazil scorer for...,1,1919 in brazilian football,date#result#score#brazil scorers#competition\n...,df['brazil scorers'].str.contains('friedenreic...,True,friedenreich be mention as a brazil scorer for...,friedenreich be mention as a brazil scorer for...
3,3,there be 2 different game where the highest sc...,1,1919 in brazilian football,date#result#score#brazil scorers#competition\n...,len(df[df['score'].str.extract(r'^(\d+) - \d+$...,True,there be 2 different game where the highest sc...,there be 2 different game where the highest sc...
4,4,4 of the 5 game be play in may 1919,1,1919 in brazilian football,date#result#score#brazil scorers#competition\n...,(df['date'].str.contains('may') & df['date'].s...,True,4 of the 5 game be play in may 1919 col : dat...,4 of the 5 game be play in may 1919 <TABLE><DE...
...,...,...,...,...,...,...,...,...,...
88111,92278,"jerraud power , 192 pound (87 kg) , be choose ...",1,2009 indianapolis colts season,round#choice#player#position#height#weight#col...,df[(df['player'] == 'jerraud powers') & (df['w...,True,"jerraud power , 192 pound (87 kg) , be choose ...","jerraud power , 192 pound (87 kg) , be choose ..."
88112,92279,terrence taylor play for auburn,0,2009 indianapolis colts season,round#choice#player#position#height#weight#col...,df[df['player'] == 'terrance taylor']['college...,False,terrence taylor play for auburn col : round |...,terrence taylor play for auburn <TABLE><DESCRI...
88113,92280,curtis painter 's position be quarterback and ...,0,2009 indianapolis colts season,round#choice#player#position#height#weight#col...,(df[df['player'] == 'curtis painter']['positio...,False,curtis painter 's position be quarterback and ...,curtis painter 's position be quarterback and ...
88114,92281,the player who weigh the most play in round 3,0,2009 indianapolis colts season,round#choice#player#position#height#weight#col...,(df.loc[df['weight'].str.extract('(\\d+)').ast...,False,the player who weigh the most play in round 3 ...,the player who weigh the most play in round 3 ...
88115,92282,"for 2007 / 08 , metal - volume (thousand tons)...",1,iran mercantile exchange,"ime exchange (including spot , credit and forw...","df.loc[df['ime exchange (including spot , cred...",True,"for 2007 / 08 , metal - volume (thousand tons)...","for 2007 / 08 , metal - volume (thousand tons)..."

In [397]:
data2['table_csv']

KeyError: 'table_csv'

In [401]:
data['table_csv']

Column(['2-1570274-4.html.csv', '2-1570274-4.html.csv', '2-1570274-4.html.csv', '2-1570274-4.html.csv', '2-1570274-4.html.csv'])

In [403]:
data['statement']

Column(['tony lema be in the top 5 for the master tournament , the us open , and the open championship', 'tournament that tony lema have participate in include the master tournament , the us open , the pga championship and the open championship', 'the only tournament that tony lema win in be the open championship', 'tony lema do not win in the us open', 'tony lema make it to the top 10 in the pga championship , but do not continue on'])

In [34]:
from datasets import load_from_disk,Dataset

In [2]:
data = load_from_disk('tab_fact_test_semtab_xml_ablation_new')

In [410]:
arr = [ i for i in data['table_csv']]
len(set(arr))

1695

In [5]:
data.filter(lambda x: x['semtab_xml_elements_top1_tresh50'] != 'None',num_proc=17)

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:00<00:00, 28516.71 examples/s]

Dataset({
    features: ['id', 'table_csv', 'table_text', 'label', 'statement', 'table_caption', 'semtab_xml_attributes_semantic_datatype_exampples_description_top1_tresh50', 'semtab_xml_attributes_datatype_exampples_description_top1_tresh50', 'semtab_xml_attributes_exampples_description_top1_tresh50', 'semtab_xml_attributes_description_top1_tresh50', 'semtab_xml_attributes_top1_tresh50', 'semtab_xml_elements_semantic_datatype_exampples_description_top1_tresh50', 'semtab_xml_elements_datatype_exampples_description_top1_tresh50', 'semtab_xml_elements_exampples_description_top1_tresh50', 'semtab_xml_elements_description_top1_tresh50', 'semtab_xml_elements_top1_tresh50', 'semtab_xml_attributes_top1_tresh50_answ', 'semtab_xml_attributes_top1_tresh50_label', 'semtab_xml_attributes_top1_tresh50_answ_correct', 'semtab_xml_elements_semantic_datatype_exampples_description_top1_tresh50_answ', 'semtab_xml_elements_semantic_datatype_exampples_description_top1_tresh50_label', 'semtab_xml_elements_semantic_datatype_exampples_description_top1_tresh50_answ_correct', 'semtab_xml_elements_datatype_exampples_description_top1_tresh50_answ', 'semtab_xml_elements_datatype_exampples_description_top1_tresh50_label', 'semtab_xml_elements_datatype_exampples_description_top1_tresh50_answ_correct', 'semtab_xml_elements_exampples_description_top1_tresh50_answ', 'semtab_xml_elements_exampples_description_top1_tresh50_label', 'semtab_xml_elements_exampples_description_top1_tresh50_answ_correct', 'semtab_xml_elements_description_top1_tresh50_answ', 'semtab_xml_elements_description_top1_tresh50_label', 'semtab_xml_elements_description_top1_tresh50_answ_correct', 'semtab_xml_elements_top1_tresh50_answ', 'semtab_xml_elements_top1_tresh50_label', 'semtab_xml_elements_top1_tresh50_answ_correct'],
    num_rows: 12779
})

In [6]:
data[3434]['semtab_xml_elements_top1_tresh50']

'<TABLE><HEADER><NAME>res</NAME></HEADER><HEADER><NAME>record</NAME></HEADER><HEADER><NAME>opponent</NAME></HEADER><HEADER><NAME>method</NAME></HEADER><HEADER><NAME>event</NAME></HEADER><HEADER><NAME>round</NAME></HEADER><HEADER><NAME>time</NAME></HEADER><HEADER><NAME>location</NAME></HEADER></TABLE>'

In [25]:
data1 = load_from_disk("tab_fact_test_semtab_xml_ablation_new")
data_continue = load_from_disk("tab_fact_test_semtab_xml_ablation_new_continue")

In [18]:
from utils.utils import load_config

In [38]:
config = load_config('semtab_xml_config_answer2.yaml')
conf_continue = load_config('semtab_xml_config_answer2_continue.yaml')

In [20]:
tests_continue = list(conf_continue.keys())
tests_continue

['semtab_xml_attributes_top1_tresh50',
 'semtab_xml_elements_semantic_datatype_exampples_description_top1_tresh50',
 'semtab_xml_elements_datatype_exampples_description_top1_tresh50',
 'semtab_xml_elements_exampples_description_top1_tresh50',
 'semtab_xml_elements_description_top1_tresh50',
 'semtab_xml_elements_top1_tresh50']

In [39]:
tests = list(config.keys())
tests

['semtab_xml_attributes_semantic_datatype_exampples_description_top1_tresh50',
 'semtab_xml_attributes_datatype_exampples_description_top1_tresh50',
 'semtab_xml_attributes_exampples_description_top1_tresh50',
 'semtab_xml_attributes_description_top1_tresh50',
 'semtab_xml_attributes_top1_tresh50',
 'semtab_xml_elements_semantic_datatype_exampples_description_top1_tresh50',
 'semtab_xml_elements_datatype_exampples_description_top1_tresh50',
 'semtab_xml_elements_exampples_description_top1_tresh50',
 'semtab_xml_elements_description_top1_tresh50',
 'semtab_xml_elements_top1_tresh50']

In [31]:
from tqdm import tqdm
# 'semtab_xml_elements_top1_tresh50_answ', 'semtab_xml_elements_top1_tresh50_label', 'semtab_xml_elements_top1_tresh50_answ_correct'
ddata1 = data1.to_dict()
for expr in tqdm(tests_continue):
    print(expr)
    ddata1[f'{expr}_answ'] = data_continue[f'{expr}_answ']
    ddata1[f'{expr}_label'] = data_continue[f'{expr}_label']
    ddata1[f'{expr}_answ_correct'] = data_continue[f'{expr}_answ_correct']

100%|██████████| 6/6 [00:00<00:00, 141.79it/s]

semtab_xml_attributes_top1_tresh50
semtab_xml_elements_semantic_datatype_exampples_description_top1_tresh50
semtab_xml_elements_datatype_exampples_description_top1_tresh50
semtab_xml_elements_exampples_description_top1_tresh50
semtab_xml_elements_description_top1_tresh50
semtab_xml_elements_top1_tresh50

In [35]:
data1 = Dataset.from_dict(ddata1)

In [37]:
data1.save_to_disk('tab_fact_test_semtab_xml_ablation_new')

Saving the dataset (1/1 shards): 100%|██████████| 12779/12779 [00:00<00:00, 39481.09 examples/s]

In [40]:
data = data1

In [41]:
acc_old = None
for test in tests:
    print(test)
    process_data = data.filter(lambda x : x[f'{test}_answ_correct'] != 'None',num_proc=17)
    dd = process_data.filter(lambda x: True if x[f'{test}_label']!='None' else False,num_proc=17)
    #print(dd.shape[0]/data.shape[0]*100)
    #print(dd.shape[0]/process_data.shape[0]*100)
    true = dd.filter(lambda x : True if x[f'{test}_label']==str(bool(x['label'])) else False,num_proc=17)
    #print(true.shape[0]/process_data.shape[0]*100)
    full = data.filter(lambda x : True if x[f'{test}_label']==str(bool(x['label'])) else False,num_proc=17)
    acc = full.shape[0]/data.shape[0]*100
    print(acc)
    if acc_old == None:
        acc_old = acc
    print('different',acc-acc_old)
    acc_old = acc

semtab_xml_attributes_semantic_datatype_exampples_description_top1_tresh50

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:16<00:00, 790.00 examples/s]
Filter (num_proc=17): 100%|██████████| 2531/2531 [00:16<00:00, 152.42 examples/s]
Filter (num_proc=17): 100%|██████████| 2531/2531 [00:16<00:00, 152.10 examples/s]
Filter (num_proc=17): 100%|██████████| 12779/12779 [00:16<00:00, 768.34 examples/s]

54.1982940762188
different 0.0
semtab_xml_attributes_datatype_exampples_description_top1_tresh50

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:16<00:00, 764.43 examples/s]
Filter (num_proc=17): 100%|██████████| 2398/2398 [00:16<00:00, 143.54 examples/s]
Filter (num_proc=17): 100%|██████████| 2398/2398 [00:16<00:00, 141.34 examples/s]
Filter (num_proc=17): 100%|██████████| 12779/12779 [00:16<00:00, 765.33 examples/s]

55.176461381954766
different 0.9781673057359654
semtab_xml_attributes_exampples_description_top1_tresh50

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:16<00:00, 761.22 examples/s]
Filter (num_proc=17): 100%|██████████| 2294/2294 [00:16<00:00, 136.85 examples/s]
Filter (num_proc=17): 100%|██████████| 2294/2294 [00:17<00:00, 134.80 examples/s]
Filter (num_proc=17): 100%|██████████| 12779/12779 [00:17<00:00, 721.67 examples/s]

54.605211675404966
different -0.5712497065497999
semtab_xml_attributes_description_top1_tresh50

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:17<00:00, 743.33 examples/s]
Filter (num_proc=17): 100%|██████████| 3003/3003 [00:16<00:00, 176.87 examples/s]
Filter (num_proc=17): 100%|██████████| 3003/3003 [00:16<00:00, 177.09 examples/s]
Filter (num_proc=17): 100%|██████████| 12779/12779 [00:16<00:00, 762.00 examples/s]

46.77987322951718
different -7.8253384458877875
semtab_xml_attributes_top1_tresh50

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:16<00:00, 756.32 examples/s]
Filter (num_proc=17): 100%|██████████| 3171/3171 [00:16<00:00, 187.26 examples/s]
Filter (num_proc=17): 100%|██████████| 3171/3171 [00:17<00:00, 185.03 examples/s]
Filter (num_proc=17): 100%|██████████| 12779/12779 [00:16<00:00, 755.26 examples/s]

46.47468503012755
different -0.30518819938962594
semtab_xml_elements_semantic_datatype_exampples_description_top1_tresh50

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:16<00:00, 753.86 examples/s]
Filter (num_proc=17): 100%|██████████| 2806/2806 [00:16<00:00, 165.42 examples/s]
Filter (num_proc=17): 100%|██████████| 2806/2806 [00:17<00:00, 164.73 examples/s]
Filter (num_proc=17): 100%|██████████| 12779/12779 [00:17<00:00, 731.47 examples/s]

52.60192503325769
different 6.12724000313014
semtab_xml_elements_datatype_exampples_description_top1_tresh50

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:16<00:00, 755.90 examples/s]
Filter (num_proc=17): 100%|██████████| 2564/2564 [00:16<00:00, 151.82 examples/s]
Filter (num_proc=17): 100%|██████████| 2564/2564 [00:17<00:00, 150.31 examples/s]
Filter (num_proc=17): 100%|██████████| 12779/12779 [00:16<00:00, 761.45 examples/s]

52.41411691055639
different -0.18780812270130554
semtab_xml_elements_exampples_description_top1_tresh50

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:16<00:00, 753.56 examples/s]
Filter (num_proc=17): 100%|██████████| 2355/2355 [00:17<00:00, 138.19 examples/s]
Filter (num_proc=17): 100%|██████████| 2355/2355 [00:16<00:00, 139.22 examples/s]
Filter (num_proc=17): 100%|██████████| 12779/12779 [00:17<00:00, 746.98 examples/s]

51.529853666171064
different -0.8842632443853233
semtab_xml_elements_description_top1_tresh50

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:16<00:00, 752.53 examples/s]
Filter (num_proc=17): 100%|██████████| 3338/3338 [00:17<00:00, 196.32 examples/s]
Filter (num_proc=17): 100%|██████████| 3338/3338 [00:16<00:00, 196.47 examples/s]
Filter (num_proc=17): 100%|██████████| 12779/12779 [00:16<00:00, 754.09 examples/s]

43.13326551373347
different -8.396588152437594
semtab_xml_elements_top1_tresh50

Filter (num_proc=17): 100%|██████████| 12779/12779 [00:17<00:00, 750.45 examples/s]
Filter (num_proc=17): 100%|██████████| 3357/3357 [00:16<00:00, 197.83 examples/s]
Filter (num_proc=17): 100%|██████████| 3357/3357 [00:17<00:00, 196.06 examples/s]
Filter (num_proc=17): 100%|██████████| 12779/12779 [00:17<00:00, 750.14 examples/s]

43.61843649737851
different 0.4851709836450411